/**
 * Maps v9 spec ## section ids to ≥1 concrete repo path (Tier A trace matrix).
 * Generated/maintained for v9-spec-trace.v9.test.ts.
 */
export const V9_SPEC_TRACE: Record<string, readonly string[]> = {
  "1": [
    "src/lib/meta-scope-s1-s6.test.ts",
    "src/lib/spec-principles.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "2": [
    "src/lib/meta-scope-s1-s6.test.ts",
    "src/lib/spec-principles.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "3": [
    "src/lib/meta-scope-s1-s6.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/acceptance-bundle.test.ts",
    "src/app/(dashboard)/contracts/intake/page.tsx",
    "src/app/(dashboard)/more/page.tsx",
    "src/components/layout/command-palette-loader.tsx",
    "src/lib/scope-constraints.test.ts",
  ],
  "4": [
    "src/lib/meta-scope-s1-s6.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "5": [
    "src/lib/meta-scope-s1-s6.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "5.1": [
    "src/lib/security-surface-guard.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "5.2": [
    "src/lib/security-surface-guard.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "5.3": [
    "src/app/(dashboard)/layout.tsx",
    "src/lib/observability/log-redaction.ts",
    "src/lib/observability/sentry-scrub.ts",
    "src/lib/compatibility-pii-minimization.test.ts",
    "src/lib/dashboard-shell-auth.test.ts",
    "src/lib/dashboard-no-dangerous-html.test.ts",
    "src/lib/user-generated-content-surfaces.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/app/api/import-export-job-org-scope.test.ts",
    "src/app/api/import-contracts-job-post-retry.test.ts",
    "src/lib/plan-enforcement-read-nav.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "5.4": [
    "src/lib/forbidden-hidden-family-core.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "6": [
    "src/lib/meta-scope-s1-s6.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "7": [
    "src/actions/onboarding-calibration.ts",
    "src/components/dashboard/onboarding-banner.tsx",
    "src/lib/onboarding-banner-activation-path.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "7.1": [
    "src/actions/onboarding-calibration.ts",
    "src/components/dashboard/onboarding-banner.tsx",
    "src/lib/onboarding-banner-activation-path.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "7.2": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/actions/onboarding-calibration.ts",
    "src/components/dashboard/onboarding-banner.tsx",
    "src/components/dashboard/onboarding-banner.ui.test.tsx",
    "src/lib/onboarding-banner-activation-path.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "7.3": [
    "src/actions/onboarding-calibration.ts",
    "src/components/dashboard/onboarding-banner.tsx",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "7.4": [
    "src/actions/onboarding-calibration.ts",
    "src/components/dashboard/onboarding-banner.tsx",
    "src/lib/onboarding-recovery-copy.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "7.5": [
    "src/actions/onboarding-calibration.ts",
    "src/components/dashboard/onboarding-banner.tsx",
    "src/lib/onboarding-banner-activation-path.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "8": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/lib/dashboard-home-composition.test.ts",
    "src/lib/plan-enforcement-read-nav.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "8.1": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/lib/dashboard-home-composition.test.ts",
    "src/lib/compatibility-dashboard-persona-density.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "8.2": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/lib/dashboard-home-composition.test.ts",
    "src/lib/compatibility-dashboard-persona-density.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "8.3": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/lib/dashboard-home-composition.test.ts",
    "src/lib/compatibility-dashboard-persona-density.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "8.4": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/lib/dashboard-home-composition.test.ts",
    "src/lib/compatibility-dashboard-persona-density.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "8.5": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/lib/dashboard-home-composition.test.ts",
    "src/lib/deep-link-query-encoding.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "8.6": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/lib/dashboard-home-composition.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "8.7": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/app/(dashboard)/layout.tsx",
    "src/components/layout/refetch-on-window-focus.tsx",
    "src/lib/dashboard-home-composition.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "9": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/lib/contracts-list-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "9.1": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/lib/contracts-list-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "9.2": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/lib/compatibility-long-title-unicode-row.test.ts",
    "src/lib/contracts-list-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "9.3": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/components/contracts/contracts-saved-view-create-form.tsx",
    "src/lib/contract-filters.ts",
    "src/lib/contract-list-id-filters.ts",
    "src/lib/contract-list-id-filters-compatibility.test.ts",
    "src/lib/contracts-search-url.ts",
    "src/lib/compatibility-cmdk-contracts-search-parity.test.ts",
    "src/lib/compatibility-renewal-horizon-contract-list-parity.test.ts",
    "src/lib/contracts-list-surface.test.ts",
    "src/lib/contracts-url-and-params.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "9.4": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/lib/contracts-list-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "9.5": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/actions/contracts-lifecycle.ts",
    "src/lib/contracts-lifecycle-surface.test.ts",
    "src/lib/contracts-list-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "9.6": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/lib/contracts-list-surface.test.ts",
    "src/lib/virtualization-selection-invariants.test.ts",
    "src/lib/compatibility-list-virtualization-contract-table.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "10": [
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/detail-page-fold-proxy.test.ts",
    "src/lib/contracts-subroutes-not-found-matrix.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "10.1": [
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/detail-page-fold-proxy.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "10.2": [
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/detail-page-fold-proxy.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "10.3": [
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/detail-page-fold-proxy.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "10.4": [
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/actions/contracts-lifecycle.ts",
    "src/lib/contracts-lifecycle-surface.test.ts",
    "src/lib/detail-page-fold-proxy.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "10.5": [
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/detail-page-fold-proxy.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "10.6": [
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/data-freshness.ts",
    "src/lib/detail-page-fold-proxy.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "11": [
    "src/components/contracts/field-review.tsx",
    "src/app/(dashboard)/contracts/review/page.tsx",
    "src/lib/review-queue-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "11.1": [
    "src/components/contracts/field-review.tsx",
    "src/app/(dashboard)/contracts/review/page.tsx",
    "src/lib/review-queue-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "11.2": [
    "src/components/contracts/field-review.tsx",
    "src/components/contracts/field-review.ui.test.tsx",
    "src/app/(dashboard)/contracts/review/page.tsx",
    "src/lib/review-queue-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "11.3": [
    "src/components/contracts/field-review.tsx",
    "src/components/contracts/field-review.ui.test.tsx",
    "src/app/(dashboard)/contracts/review/page.tsx",
    "src/lib/review-queue-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "11.4": [
    "src/components/contracts/field-review.tsx",
    "src/app/(dashboard)/contracts/review/page.tsx",
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/review-save-next-telemetry-link.tsx",
    "src/lib/review-queue-surface.test.ts",
    "src/lib/execution-engine-bridge.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "11.5": [
    "src/components/contracts/field-review.tsx",
    "src/app/(dashboard)/contracts/review/page.tsx",
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/review-save-next-telemetry-link.tsx",
    "src/lib/review-queue-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "12": [
    "src/app/(dashboard)/work/page.tsx",
    "src/components/ui/permission-eligibility-hint.tsx",
    "src/components/work/work-queue-inline-actions.tsx",
    "src/components/work/work-queue-inline-actions-gate.tsx",
    "src/lib/compatibility-work-queue-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "12.1": [
    "src/app/(dashboard)/work/page.tsx",
    "src/components/ui/permission-eligibility-hint.tsx",
    "src/components/work/work-queue-inline-actions.tsx",
    "src/components/work/work-queue-inline-actions-gate.tsx",
    "src/lib/compatibility-work-queue-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "12.2": [
    "src/app/(dashboard)/work/page.tsx",
    "src/lib/compatibility-work-lens-empty-states.test.ts",
    "src/lib/business-dates.ts",
    "src/lib/business-dates-drift.test.ts",
    "src/components/ui/permission-eligibility-hint.tsx",
    "src/components/work/work-queue-inline-actions.tsx",
    "src/components/work/work-queue-inline-actions-gate.tsx",
    "src/lib/compatibility-work-queue-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "12.3": [
    "src/app/(dashboard)/work/page.tsx",
    "src/components/ui/permission-eligibility-hint.tsx",
    "src/components/work/work-queue-inline-actions.tsx",
    "src/components/work/work-queue-inline-actions-gate.tsx",
    "src/lib/permission-eligibility-work-queue.test.ts",
    "src/lib/tasks-obligations-distinct-language.test.ts",
    "src/lib/compatibility-work-queue-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "12.4": [
    "src/app/(dashboard)/work/page.tsx",
    "src/components/ui/permission-eligibility-hint.tsx",
    "src/components/work/work-queue-inline-actions.tsx",
    "src/components/work/work-queue-inline-actions-gate.tsx",
    "src/lib/compatibility-work-queue-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "12.5": [
    "src/app/(dashboard)/work/page.tsx",
    "src/components/ui/permission-eligibility-hint.tsx",
    "src/components/work/work-queue-inline-actions.tsx",
    "src/components/work/work-queue-inline-actions.ui.test.tsx",
    "src/components/work/work-queue-inline-actions-gate.tsx",
    "src/lib/tasks-obligations-distinct-language.test.ts",
    "src/lib/compatibility-work-queue-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "13": [
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/components/contracts/renewal-row-checklist-actions.tsx",
    "src/lib/renewals-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "13.1": [
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/components/contracts/renewal-row-checklist-actions.tsx",
    "src/lib/renewals-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "13.2": [
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/lib/sparse-records.ts",
    "src/lib/sparse-records.test.ts",
    "src/components/contracts/renewal-row-checklist-actions.tsx",
    "src/lib/renewals-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "13.3": [
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/components/contracts/renewal-row-checklist-actions.tsx",
    "src/lib/contract-filters.ts",
    "src/lib/compatibility-renewal-horizon-contract-list-parity.test.ts",
    "src/lib/renewal-next-action.ts",
    "src/lib/renewal-next-action.test.ts",
    "src/lib/renewals-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "13.4": [
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/components/contracts/renewal-row-checklist-actions.tsx",
    "src/lib/renewals-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "13.5": [
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/components/contracts/renewal-row-checklist-actions.tsx",
    "src/lib/renewals-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "14": [
    "src/app/(dashboard)/contracts/exceptions/page.tsx",
    "src/actions/exceptions.ts",
    "src/components/contracts/exception-mutation-panels.tsx",
    "src/lib/exceptions-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "14.1": [
    "src/app/(dashboard)/contracts/exceptions/page.tsx",
    "src/actions/exceptions.ts",
    "src/components/contracts/exception-mutation-panels.tsx",
    "src/lib/exceptions-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "14.2": [
    "src/app/(dashboard)/contracts/exceptions/page.tsx",
    "src/actions/exceptions.ts",
    "src/components/contracts/exception-mutation-panels.tsx",
    "src/lib/exceptions-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "14.3": [
    "src/app/(dashboard)/contracts/exceptions/page.tsx",
    "src/actions/exceptions.ts",
    "src/lib/exception-priority.ts",
    "src/lib/exceptions-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "14.4": [
    "src/app/(dashboard)/contracts/exceptions/page.tsx",
    "src/actions/exceptions.ts",
    "src/components/contracts/exception-mutation-panels.tsx",
    "src/lib/exceptions-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "14.5": [
    "src/app/(dashboard)/contracts/exceptions/page.tsx",
    "src/actions/exceptions.ts",
    "src/lib/exception-audit-trail-nonclutter.test.ts",
    "src/lib/exceptions-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "15": [
    "src/app/(dashboard)/contracts/evidence-studio/page.tsx",
    "src/lib/evidence-display.ts",
    "src/lib/evidence-display.test.ts",
    "src/app/api/evidence/[id]/[action]/route.ts",
    "src/lib/api-critical-routes-matrix.test.ts",
    "src/lib/compatibility-evidence-studio-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "15.1": [
    "src/app/(dashboard)/contracts/evidence-studio/page.tsx",
    "src/app/api/evidence/[id]/[action]/route.ts",
    "src/lib/compatibility-evidence-studio-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "15.2": [
    "src/app/(dashboard)/contracts/evidence-studio/page.tsx",
    "src/lib/evidence-display.ts",
    "src/lib/evidence-display.test.ts",
    "src/app/api/evidence/[id]/[action]/route.ts",
    "src/lib/compatibility-evidence-studio-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "15.3": [
    "src/app/(dashboard)/contracts/evidence-studio/page.tsx",
    "src/components/contracts/evidence-submission-form.tsx",
    "src/app/api/evidence/[id]/[action]/route.ts",
    "src/lib/compatibility-evidence-studio-surface.test.ts",
    "src/lib/form-preserve-on-reject.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "15.4": [
    "src/app/(dashboard)/contracts/evidence-studio/page.tsx",
    "src/lib/evidence-display.ts",
    "src/lib/evidence-display.test.ts",
    "src/components/contracts/contract-evidence-requirements-panel.tsx",
    "src/components/contracts/contract-evidence-requirements-panel.ui.test.tsx",
    "src/app/api/evidence/[id]/[action]/route.ts",
    "src/lib/compatibility-evidence-studio-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "15.5": [
    "src/app/(dashboard)/contracts/evidence-studio/page.tsx",
    "src/components/contracts/evidence-submission-review-actions.tsx",
    "src/app/api/evidence/[id]/[action]/route.ts",
    "src/lib/compatibility-evidence-studio-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "16": [
    "src/components/layout/command-palette.tsx",
    "src/lib/product-surface/cmdk-search-jumps.ts",
    "src/lib/search-cmdk-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "16.1": [
    "src/components/layout/command-palette.tsx",
    "src/lib/product-surface/cmdk-search-jumps.ts",
    "src/lib/contracts-search-url.ts",
    "src/lib/compatibility-cmdk-contracts-search-parity.test.ts",
    "src/lib/deep-link-query-encoding.test.ts",
    "src/lib/search-cmdk-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "16.2": [
    "src/components/layout/command-palette.tsx",
    "e2e/compatibility-core-smoke.spec.ts",
    "src/lib/product-surface/cmdk-search-jumps.ts",
    "src/lib/product-surface/cmdk-search-jumps.test.ts",
    "src/lib/search-cmdk-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "16.3": [
    "src/components/layout/command-palette.tsx",
    "e2e/compatibility-core-smoke.spec.ts",
    "src/lib/product-surface/cmdk-search-jumps.ts",
    "src/lib/search-cmdk-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "16.4": [
    "src/components/layout/command-palette.tsx",
    "e2e/compatibility-core-smoke.spec.ts",
    "src/lib/product-surface/cmdk-search-jumps.ts",
    "src/lib/search-cmdk-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "16.5": [
    "src/components/layout/command-palette.tsx",
    "src/lib/product-surface/cmdk-search-jumps.ts",
    "src/lib/search-cmdk-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "17": [
    "src/lib/import-jobs.ts",
    "src/lib/extraction/run-pipeline.ts",
    "src/app/api/import/contracts/[jobId]/route.ts",
    "src/lib/api-critical-routes-matrix.test.ts",
    "src/lib/import-export-surfaces.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "17.1": [
    "src/lib/import-jobs.ts",
    "src/lib/extraction/run-pipeline.ts",
    "src/app/api/import/contracts/[jobId]/route.ts",
    "src/lib/import-export-surfaces.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "17.2": [
    "src/lib/import-jobs.ts",
    "src/lib/extraction/run-pipeline.ts",
    "src/app/api/import/contracts/[jobId]/route.ts",
    "src/components/contracts/import-job-retry-button.tsx",
    "src/components/contracts/import-job-retry-button.ui.test.tsx",
    "src/lib/import-export-surfaces.test.ts",
    "src/lib/upload-import-http-error-copy.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "17.3": [
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/import-jobs.ts",
    "src/lib/extraction/run-pipeline.ts",
    "src/app/api/import/contracts/[jobId]/route.ts",
    "src/lib/import-export-surfaces.test.ts",
    "src/lib/extraction-job-alert-states.test.ts",
    "src/lib/compatibility-extraction-queued-vs-in-progress-ui.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "17.4": [
    "src/lib/import-job-visibility.ts",
    "src/lib/import-job-visibility.test.ts",
    "src/lib/outcome-semantics.ts",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/import-jobs.ts",
    "src/lib/extraction/run-pipeline.ts",
    "src/app/api/import/contracts/[jobId]/route.ts",
    "src/lib/import-export-surfaces.test.ts",
    "src/lib/extraction-job-alert-states.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "17.5": [
    "src/lib/import-jobs.ts",
    "src/lib/extraction/run-pipeline.ts",
    "src/app/api/import/contracts/[jobId]/route.ts",
    "src/lib/import-export-surfaces.test.ts",
    "src/lib/supabase-050-read-write-ui.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "18": [
    "src/lib/notification-delivery.ts",
    "src/lib/reminder-delivery-visibility.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "18.1": [
    "src/lib/notification-delivery.ts",
    "src/lib/reminder-delivery-visibility.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "18.2": [
    "src/lib/notification-delivery.ts",
    "src/lib/reminder-delivery-visibility.ts",
    "src/lib/in-app-notification-display.ts",
    "src/lib/notification-deeplink-matrix.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "18.3": [
    "src/lib/notification-delivery.ts",
    "src/lib/reminder-delivery-visibility.ts",
    "src/lib/notification-internal-deeplink.ts",
    "src/lib/product-surface/cmdk-search-jumps.ts",
    "src/app/(dashboard)/contracts/collaboration/page.tsx",
    "src/lib/notification-deeplink-matrix.test.ts",
    "src/lib/deep-link-query-encoding.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "18.4": [
    "src/lib/notification-delivery.ts",
    "src/lib/reminder-delivery-visibility.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "18.5": [
    "src/lib/notification-delivery.ts",
    "src/lib/reminder-delivery-visibility.ts",
    "src/lib/in-app-notification-display.ts",
    "src/lib/in-app-notification-display.test.ts",
    "src/app/(dashboard)/contracts/collaboration/page.tsx",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "19": [
    "src/app/(dashboard)/reports/page.tsx",
    "src/app/api/export/contracts/route.ts",
    "src/lib/api-critical-routes-matrix.test.ts",
    "src/lib/import-export-surfaces.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "19.1": [
    "src/app/(dashboard)/reports/page.tsx",
    "src/app/api/export/contracts/route.ts",
    "src/lib/import-export-surfaces.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "19.2": [
    "src/app/(dashboard)/reports/page.tsx",
    "src/app/api/export/contracts/route.ts",
    "src/lib/import-export-surfaces.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "19.3": [
    "src/lib/export-job-visibility.ts",
    "src/lib/export-job-visibility.test.ts",
    "src/lib/outcome-semantics.ts",
    "src/app/(dashboard)/reports/page.tsx",
    "src/app/api/export/contracts/route.ts",
    "src/app/api/export/review-packet/route.ts",
    "src/lib/csv-formula-safe.ts",
    "src/lib/csv-formula-safe.test.ts",
    "src/lib/import-export-surfaces.test.ts",
    "src/lib/export-csv-workspace-gate.test.ts",
    "src/lib/supabase-050-read-write-ui.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "19.4": [
    "src/app/(dashboard)/reports/page.tsx",
    "src/app/api/export/contracts/route.ts",
    "src/lib/export-contract-csv-field-policy.ts",
    "src/lib/import-export-surfaces.test.ts",
    "src/lib/export-csv-workspace-gate.test.ts",
    "src/lib/export-csv-core-column-suppression.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "20": [
    "src/components/ui/empty-state.tsx",
    "src/lib/empty-state-prohibitions.test.ts",
    "src/lib/empty-states-high-traffic.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "20.1": [
    "src/lib/compatibility-work-lens-empty-states.test.ts",
    "src/components/ui/empty-state.tsx",
    "src/lib/empty-state-prohibitions.test.ts",
    "src/lib/empty-states-high-traffic.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "20.2": [
    "src/components/ui/empty-state.tsx",
    "src/lib/empty-state-prohibitions.test.ts",
    "src/lib/empty-states-high-traffic.test.ts",
    "src/lib/empty-state-cta-primitive.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "20.3": [
    "src/lib/forbidden-hidden-family-core.test.ts",
    "src/components/ui/empty-state.tsx",
    "src/lib/empty-state-prohibitions.test.ts",
    "src/lib/empty-states-high-traffic.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "21": [
    "src/app/(dashboard)/loading-error-consistency.test.ts",
    "src/lib/mutation-feedback-surface.test.ts",
    "src/lib/coverage-inventory.test.ts",
    "src/app/(dashboard)/loading.tsx",
    "src/app/(dashboard)/dashboard/loading.tsx",
    "src/app/(dashboard)/contracts/loading.tsx",
    "src/app/(dashboard)/reports/loading.tsx",
    "src/app/(dashboard)/settings/loading.tsx",
    "src/app/(dashboard)/assurance/loading.tsx",
    "src/app/(dashboard)/decisions/loading.tsx",
    "src/app/(dashboard)/dashboard/persona/loading.tsx",
    "src/app/(dashboard)/onboarding/calibration/loading.tsx",
    "src/app/(dashboard)/contracts/analytics/loading.tsx",
    "src/app/(dashboard)/contracts/tasks/loading.tsx",
    "src/app/(dashboard)/contracts/reports/loading.tsx",
    "src/app/(dashboard)/contracts/data-quality/loading.tsx",
    "src/app/(dashboard)/contracts/[id]/loading.tsx",
    "src/app/(dashboard)/work/loading.tsx",
    "src/app/(dashboard)/contracts/renewals/loading.tsx",
    "src/app/(dashboard)/contracts/exceptions/loading.tsx",
    "src/app/(dashboard)/contracts/evidence-studio/loading.tsx",
    "src/app/(dashboard)/contracts/review/loading.tsx",
    "src/app/(dashboard)/contracts/bulk/loading.tsx",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "21.1": [
    "src/app/(dashboard)/loading-error-consistency.test.ts",
    "src/lib/mutation-feedback-surface.test.ts",
    "src/lib/coverage-inventory.test.ts",
    "src/app/(dashboard)/loading.tsx",
    "src/app/(dashboard)/dashboard/loading.tsx",
    "src/app/(dashboard)/contracts/loading.tsx",
    "src/app/(dashboard)/reports/loading.tsx",
    "src/app/(dashboard)/settings/loading.tsx",
    "src/app/(dashboard)/assurance/loading.tsx",
    "src/app/(dashboard)/decisions/loading.tsx",
    "src/app/(dashboard)/dashboard/persona/loading.tsx",
    "src/app/(dashboard)/onboarding/calibration/loading.tsx",
    "src/app/(dashboard)/contracts/analytics/loading.tsx",
    "src/app/(dashboard)/contracts/tasks/loading.tsx",
    "src/app/(dashboard)/contracts/reports/loading.tsx",
    "src/app/(dashboard)/contracts/data-quality/loading.tsx",
    "src/app/(dashboard)/contracts/[id]/loading.tsx",
    "src/app/(dashboard)/work/loading.tsx",
    "src/app/(dashboard)/contracts/renewals/loading.tsx",
    "src/app/(dashboard)/contracts/exceptions/loading.tsx",
    "src/app/(dashboard)/contracts/evidence-studio/loading.tsx",
    "src/app/(dashboard)/contracts/review/loading.tsx",
    "src/app/(dashboard)/contracts/bulk/loading.tsx",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "21.2": [
    "src/app/(dashboard)/loading-error-consistency.test.ts",
    "src/lib/mutation-feedback-surface.test.ts",
    "src/lib/coverage-inventory.test.ts",
    "src/app/(dashboard)/loading.tsx",
    "src/app/(dashboard)/dashboard/loading.tsx",
    "src/app/(dashboard)/contracts/loading.tsx",
    "src/app/(dashboard)/reports/loading.tsx",
    "src/app/(dashboard)/settings/loading.tsx",
    "src/app/(dashboard)/assurance/loading.tsx",
    "src/app/(dashboard)/decisions/loading.tsx",
    "src/app/(dashboard)/dashboard/persona/loading.tsx",
    "src/app/(dashboard)/onboarding/calibration/loading.tsx",
    "src/app/(dashboard)/contracts/analytics/loading.tsx",
    "src/app/(dashboard)/contracts/tasks/loading.tsx",
    "src/app/(dashboard)/contracts/reports/loading.tsx",
    "src/app/(dashboard)/contracts/data-quality/loading.tsx",
    "src/app/(dashboard)/contracts/[id]/loading.tsx",
    "src/app/(dashboard)/work/loading.tsx",
    "src/app/(dashboard)/contracts/renewals/loading.tsx",
    "src/app/(dashboard)/contracts/exceptions/loading.tsx",
    "src/app/(dashboard)/contracts/evidence-studio/loading.tsx",
    "src/app/(dashboard)/contracts/review/loading.tsx",
    "src/app/(dashboard)/contracts/bulk/loading.tsx",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "21.3": [
    "src/app/(dashboard)/loading-error-consistency.test.ts",
    "src/lib/mutation-feedback-surface.test.ts",
    "src/lib/optimistic-mutation-inventory.test.ts",
    "src/lib/coverage-inventory.test.ts",
    "src/app/(dashboard)/loading.tsx",
    "src/app/(dashboard)/dashboard/loading.tsx",
    "src/app/(dashboard)/contracts/loading.tsx",
    "src/app/(dashboard)/reports/loading.tsx",
    "src/app/(dashboard)/settings/loading.tsx",
    "src/app/(dashboard)/assurance/loading.tsx",
    "src/app/(dashboard)/decisions/loading.tsx",
    "src/app/(dashboard)/dashboard/persona/loading.tsx",
    "src/app/(dashboard)/onboarding/calibration/loading.tsx",
    "src/app/(dashboard)/contracts/analytics/loading.tsx",
    "src/app/(dashboard)/contracts/tasks/loading.tsx",
    "src/app/(dashboard)/contracts/reports/loading.tsx",
    "src/app/(dashboard)/contracts/data-quality/loading.tsx",
    "src/app/(dashboard)/contracts/[id]/loading.tsx",
    "src/app/(dashboard)/work/loading.tsx",
    "src/app/(dashboard)/contracts/renewals/loading.tsx",
    "src/app/(dashboard)/contracts/exceptions/loading.tsx",
    "src/app/(dashboard)/contracts/evidence-studio/loading.tsx",
    "src/app/(dashboard)/contracts/review/loading.tsx",
    "src/app/(dashboard)/contracts/bulk/loading.tsx",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "21.4": [
    "src/app/(dashboard)/loading-error-consistency.test.ts",
    "src/lib/revalidate-cache-stability.test.ts",
    "src/lib/mutation-feedback-surface.test.ts",
    "src/lib/coverage-inventory.test.ts",
    "src/app/(dashboard)/loading.tsx",
    "src/app/(dashboard)/dashboard/loading.tsx",
    "src/app/(dashboard)/contracts/loading.tsx",
    "src/app/(dashboard)/reports/loading.tsx",
    "src/app/(dashboard)/settings/loading.tsx",
    "src/app/(dashboard)/assurance/loading.tsx",
    "src/app/(dashboard)/decisions/loading.tsx",
    "src/app/(dashboard)/dashboard/persona/loading.tsx",
    "src/app/(dashboard)/onboarding/calibration/loading.tsx",
    "src/app/(dashboard)/contracts/analytics/loading.tsx",
    "src/app/(dashboard)/contracts/tasks/loading.tsx",
    "src/app/(dashboard)/contracts/reports/loading.tsx",
    "src/app/(dashboard)/contracts/data-quality/loading.tsx",
    "src/app/(dashboard)/contracts/[id]/loading.tsx",
    "src/app/(dashboard)/work/loading.tsx",
    "src/app/(dashboard)/contracts/renewals/loading.tsx",
    "src/app/(dashboard)/contracts/exceptions/loading.tsx",
    "src/app/(dashboard)/contracts/evidence-studio/loading.tsx",
    "src/app/(dashboard)/contracts/review/loading.tsx",
    "src/app/(dashboard)/contracts/bulk/loading.tsx",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "22": [
    "src/lib/recoverable-mutation-error.ts",
    "src/lib/api-client-errors.ts",
    "src/app/(dashboard)/error.tsx",
    "src/app/(marketing)/error.tsx",
    "src/lib/errors-recovery-surface.test.ts",
    "src/lib/client-exception-capture.test.ts",
    "src/lib/contracts-subroutes-not-found-matrix.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "22.1": [
    "src/lib/recoverable-mutation-error.ts",
    "src/lib/api-client-errors.ts",
    "src/lib/api-client-errors.test.ts",
    "src/app/(dashboard)/error.tsx",
    "src/app/(marketing)/error.tsx",
    "src/lib/errors-recovery-surface.test.ts",
    "src/lib/client-exception-capture.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "22.2": [
    "src/lib/recoverable-mutation-error.ts",
    "src/lib/api-client-errors.ts",
    "src/app/(dashboard)/error.tsx",
    "src/app/(marketing)/error.tsx",
    "src/lib/errors-recovery-surface.test.ts",
    "src/lib/form-preserve-on-reject.test.ts",
    "src/lib/client-exception-capture.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "22.3": [
    "src/lib/recoverable-mutation-error.ts",
    "src/lib/api-client-errors.ts",
    "src/app/(dashboard)/error.tsx",
    "src/app/(marketing)/error.tsx",
    "src/lib/errors-recovery-surface.test.ts",
    "src/lib/client-exception-capture.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "22.4": [
    "src/lib/recoverable-mutation-error.ts",
    "src/lib/api-client-errors.ts",
    "src/app/(dashboard)/error.tsx",
    "src/app/(marketing)/error.tsx",
    "src/lib/errors-recovery-surface.test.ts",
    "src/lib/client-exception-capture.test.ts",
    "src/lib/dashboard-no-dangerous-html.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "23": [
    "src/components/layout/page-load-reporter.tsx",
    "src/actions/product-telemetry.ts",
    "src/lib/performance-page-load-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "23.1": [
    "src/components/layout/page-load-reporter.tsx",
    "src/actions/product-telemetry.ts",
    "src/lib/performance-page-load-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "23.2": [
    "src/components/layout/page-load-reporter.tsx",
    "src/actions/product-telemetry.ts",
    "src/lib/performance-page-load-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "23.3": [
    "src/components/layout/page-load-reporter.tsx",
    "src/actions/product-telemetry.ts",
    "src/lib/performance-page-load-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "23.4": [
    "src/components/layout/page-load-reporter.tsx",
    "src/actions/product-telemetry.ts",
    "src/lib/performance-page-load-surface.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "24": [
    "src/lib/navigation.ts",
    "src/lib/contracts.ts",
    "src/lib/contract-list.ts",
    "src/lib/business-dates.ts",
    "src/lib/timezone-date-format-sweep.test.ts",
    "src/lib/consistency-vocabulary-core.test.ts",
    "src/lib/route-metadata-core-anchors.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "24.1": [
    "src/lib/navigation.ts",
    "src/lib/contracts.ts",
    "src/lib/contract-list.ts",
    "src/lib/consistency-vocabulary-core.test.ts",
    "src/lib/review-cadence-vs-queue-labels.test.ts",
    "src/lib/route-metadata-core-anchors.test.ts",
    "src/lib/tasks-obligations-distinct-language.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "24.2": [
    "src/lib/navigation.ts",
    "src/lib/contracts.ts",
    "src/lib/contract-list.ts",
    "src/lib/consistency-vocabulary-core.test.ts",
    "src/lib/tasks-obligations-distinct-language.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "24.3": [
    "src/lib/navigation.ts",
    "src/lib/contracts.ts",
    "src/lib/contract-list.ts",
    "src/app/(dashboard)/contracts/watchlists/page.tsx",
    "src/lib/consistency-vocabulary-core.test.ts",
    "src/lib/cross-surface-contract-status-labels.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "24.4": [
    "src/lib/navigation.ts",
    "src/lib/contracts.ts",
    "src/lib/contract-list.ts",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/app/(dashboard)/contracts/watchlists/page.tsx",
    "src/lib/consistency-vocabulary-core.test.ts",
    "src/lib/route-metadata-core-anchors.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "24.5": [
    "src/lib/navigation.ts",
    "src/lib/contracts.ts",
    "src/lib/contract-list.ts",
    "src/lib/consistency-vocabulary-core.test.ts",
    "src/lib/route-metadata-core-anchors.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "25": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/app/(dashboard)/contracts/tasks/page.tsx",
    "src/app/(dashboard)/contracts/obligations/page.tsx",
    "src/app/(dashboard)/contracts/watchlists/page.tsx",
    "src/lib/contract-table-a11y-responsive.test.ts",
    "src/lib/workspace-tables-scroll.test.ts",
    "src/components/layout/command-palette.ui.test.tsx",
    "e2e/a11y.keyboard.spec.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "25.1": [
    "src/app/layout.tsx",
    "src/components/layout/skip-link.tsx",
    "src/app/(dashboard)/layout.tsx",
    "src/lib/skip-link-landmarks.test.ts",
    "src/components/contracts/contract-table.tsx",
    "src/lib/contract-table-a11y-responsive.test.ts",
    "src/components/layout/command-palette.ui.test.tsx",
    "e2e/a11y.keyboard.spec.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "25.2": [
    "src/components/contracts/contract-table.tsx",
    "src/lib/contract-table-a11y-responsive.test.ts",
    "src/components/layout/command-palette.ui.test.tsx",
    "e2e/a11y.keyboard.spec.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "25.3": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/app/(dashboard)/contracts/tasks/page.tsx",
    "src/app/(dashboard)/contracts/obligations/page.tsx",
    "src/app/(dashboard)/contracts/watchlists/page.tsx",
    "src/lib/contract-table-a11y-responsive.test.ts",
    "src/lib/workspace-tables-scroll.test.ts",
    "src/components/layout/command-palette.ui.test.tsx",
    "e2e/a11y.keyboard.spec.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "26": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/app/(dashboard)/contracts/tasks/page.tsx",
    "src/app/(dashboard)/contracts/obligations/page.tsx",
    "src/app/(dashboard)/contracts/watchlists/page.tsx",
    "src/lib/contract-table-a11y-responsive.test.ts",
    "src/lib/workspace-tables-scroll.test.ts",
    "src/app/(dashboard)/layout.tsx",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "26.1": [
    "src/components/contracts/contract-table.tsx",
    "src/lib/contract-table-a11y-responsive.test.ts",
    "src/app/(dashboard)/layout.tsx",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "26.2": [
    "src/components/contracts/contract-table.tsx",
    "src/lib/compatibility-long-title-unicode-row.test.ts",
    "src/lib/contract-table-a11y-responsive.test.ts",
    "src/app/(dashboard)/layout.tsx",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "26.3": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/app/(dashboard)/contracts/tasks/page.tsx",
    "src/app/(dashboard)/contracts/obligations/page.tsx",
    "src/app/(dashboard)/contracts/watchlists/page.tsx",
    "src/lib/contract-table-a11y-responsive.test.ts",
    "src/lib/workspace-tables-scroll.test.ts",
    "src/app/(dashboard)/layout.tsx",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "27": [
    "src/lib/data-freshness.ts",
    "src/lib/job-lifecycle-copy.ts",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/app/(dashboard)/settings/health/page.tsx",
    "src/lib/reliability-states-27-2.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "27.1": [
    "src/lib/data-freshness.ts",
    "src/lib/job-lifecycle-copy.ts",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/app/(dashboard)/settings/health/page.tsx",
    "src/lib/reliability-states-27-2.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "27.2": [
    "src/lib/data-freshness.ts",
    "src/lib/job-lifecycle-copy.ts",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/app/(dashboard)/settings/health/page.tsx",
    "src/lib/reminder-delivery-visibility.ts",
    "src/lib/reminder-inactive-missing-dates-copy.test.ts",
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/lib/supabase-050-read-write-ui.test.ts",
    "src/app/(dashboard)/reports/page.tsx",
    "src/app/(dashboard)/reports/reports-control-room-reliability.test.ts",
    "src/lib/reliability-states-27-2.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "27.3": [
    "src/lib/data-freshness.ts",
    "src/lib/job-lifecycle-copy.ts",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/app/(dashboard)/settings/health/page.tsx",
    "src/lib/reliability-states-27-2.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "27.4": [
    "src/lib/data-freshness.ts",
    "src/lib/job-lifecycle-copy.ts",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/app/(dashboard)/settings/health/page.tsx",
    "src/lib/reliability-states-27-2.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "28": [
    "src/lib/product-telemetry.ts",
    "src/lib/product-telemetry.details.test.ts",
    "src/lib/observability/log-redaction.ts",
    "src/lib/compatibility-pii-minimization.test.ts",
    "src/lib/product-telemetry.wiring.test.ts",
    "src/lib/telemetry-tier-c-paths.test.ts",
    "src/lib/product-telemetry-swallow-errors.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "28.1": [
    "src/lib/product-telemetry.ts",
    "src/lib/product-telemetry.wiring.test.ts",
    "src/lib/telemetry-tier-c-paths.test.ts",
    "src/lib/product-telemetry-swallow-errors.test.ts",
    "src/lib/product-telemetry-client-nonblocking.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "28.2": [
    "src/lib/metric-definitions.ts",
    "src/lib/metric-definitions.test.ts",
    "src/lib/product-telemetry.ts",
    "src/lib/product-telemetry.wiring.test.ts",
    "src/lib/telemetry-tier-c-paths.test.ts",
    "src/lib/product-telemetry-swallow-errors.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "28.3": [
    "src/actions/onboarding-calibration.ts",
    "src/lib/product-telemetry.ts",
    "src/lib/product-telemetry.wiring.test.ts",
    "src/lib/auditability-actions-28-3.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "29": [
    "src/lib/plan-enforcement-bundles.test.ts",
    "src/lib/appendix-verbatim-anchors.test.ts",
    "src/lib/regression-bridge.test.ts",
    "src/lib/regression-acceptance-anchors.test.ts",
    "src/lib/coverage-inventory.test.ts",
    "src/lib/acceptance-criteria.test.ts",
    "src/lib/acceptance-scripts-sync.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "29.1": [
    "src/lib/plan-enforcement-bundles.test.ts",
    "src/lib/appendix-verbatim-anchors.test.ts",
    "src/lib/regression-bridge.test.ts",
    "src/lib/regression-acceptance-anchors.test.ts",
    "src/lib/coverage-inventory.test.ts",
    "src/lib/api-critical-routes-matrix.test.ts",
    "src/lib/acceptance-criteria.test.ts",
    "src/lib/acceptance-scripts-sync.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "29.2": [
    "src/lib/plan-enforcement-bundles.test.ts",
    "src/lib/appendix-verbatim-anchors.test.ts",
    "src/lib/regression-bridge.test.ts",
    "src/lib/regression-acceptance-anchors.test.ts",
    "src/lib/coverage-inventory.test.ts",
    "src/lib/acceptance-criteria.test.ts",
    "src/lib/acceptance-scripts-sync.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "30": [
    "src/lib/completion-proxies.test.ts",
    "src/lib/measurable-proxies-anchor.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "30.1": [
    "src/lib/completion-proxies.test.ts",
    "src/lib/measurable-proxies-anchor.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "30.2": [
    "src/lib/completion-proxies.test.ts",
    "src/lib/measurable-proxies-anchor.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "30.3": [
    "src/lib/completion-proxies.test.ts",
    "src/lib/measurable-proxies-anchor.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "30.4": [
    "src/lib/completion-proxies.test.ts",
    "src/lib/measurable-proxies-anchor.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "30.5": [
    "src/lib/completion-proxies.test.ts",
    "src/lib/measurable-proxies-anchor.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "30.6": [
    "src/lib/completion-proxies.test.ts",
    "src/lib/measurable-proxies-anchor.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "30.7": [
    "src/lib/completion-proxies.test.ts",
    "src/lib/measurable-proxies-anchor.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "30.8": [
    "src/lib/completion-proxies.test.ts",
    "src/lib/measurable-proxies-anchor.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "30.9": [
    "src/components/layout/page-load-reporter.tsx",
    "src/lib/client-telemetry-strictmode.test.ts",
    "src/lib/completion-proxies.test.ts",
    "src/lib/measurable-proxies-anchor.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "30.10": [
    "src/lib/completion-proxies.test.ts",
    "src/lib/measurable-proxies-anchor.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "31": [
    "src/lib/global-constraints.test.ts",
    "src/lib/plan-enforcement-bundles.test.ts",
    "src/lib/non-goals-guardrails-s31-s32.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
  "32": [
    "src/lib/rollout.ts",
    "src/lib/rollout-inline-queue-kill-switch.test.ts",
    "src/lib/rollout-migrations.test.ts",
    "src/lib/spec-principles.test.ts",
    "src/lib/plan-enforcement-bundles.test.ts",
    "src/lib/non-goals-guardrails-s31-s32.test.ts",
    "src/lib/security-surface-guard.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/acceptance-bundle.test.ts",
  ],
} as const;

// Version-name compatibility aliases. Prefer neutral exports in new code.
export { V9_SPEC_TRACE as SPEC_TRACE };
// End version-name compatibility aliases.
