export const V10_SPEC_TRACE: Record<string, readonly string[]> = {
  "1": ["src/lib/release-contract.ts", "src/lib/release-contract.test.ts"],
  "2": ["src/lib/release-contract.ts", "src/lib/objective-measurements.test.ts"],
  "2.1": ["src/lib/objective-measurements.ts", "src/lib/objective-measurements.test.ts"],
  "2.2": ["src/lib/release-evidence.ts", "src/lib/release-evidence.test.ts"],
  "3": ["src/lib/release-contract.ts", "src/lib/governance.ts", "src/lib/hardening-contracts.test.ts"],
  "3.1": ["src/lib/release-contract.ts", "src/lib/release-contract.test.ts"],
  "3.1.1": ["src/lib/readiness-scorecard.ts", "src/lib/readiness-scorecard.test.ts"],
  "3.2": ["src/lib/work-semantics.ts", "src/lib/semantics.test.ts"],
  "3.3": ["src/lib/contract-health.ts", "src/lib/semantics.test.ts"],
  "3.4": ["src/lib/governance.ts", "src/lib/semantics.test.ts"],
  "3.5": ["src/lib/hardening-contracts.ts", "src/lib/hardening-contracts.test.ts"],
  "4": ["src/lib/ui-state-contracts.ts", "src/lib/ui-state-contracts.test.ts"],
  "4.1": ["src/lib/activation-state.ts", "src/app/api/import/contracts/route.ts", "src/lib/semantics.test.ts"],
  "4.2": ["src/lib/work-semantics.ts", "src/lib/work-hub-lens.ts", "src/app/(dashboard)/work/page.tsx", "src/lib/semantics.test.ts"],
  "4.3": ["src/app/(dashboard)/dashboard/page.tsx", "src/lib/ui-state-contracts.ts", "src/lib/ui-state-contracts.test.ts"],
  "4.4": ["src/lib/contract-health.ts", "src/lib/contract-detail-summary.ts", "src/lib/semantics.test.ts"],
  "4.5": ["src/lib/field-provenance.ts", "src/lib/release-contract.ts", "src/lib/semantics.test.ts"],
  "4.6": ["src/lib/renewal-posture.ts", "src/lib/semantics.test.ts"],
  "4.7": ["src/lib/evidence-collaboration.ts", "src/app/api/cron/v4/evidence-followup/route.ts", "src/lib/semantics.test.ts"],
  "4.8": ["src/lib/approval-exception.ts", "src/actions/approvals.ts", "src/actions/exceptions.ts", "src/actions/tasks.ts", "src/lib/operational-contracts.test.ts"],
  "4.9": ["src/app/api/command-palette/contracts/route.ts", "src/components/layout/command-palette.tsx", "src/components/layout/command-palette.ui.test.tsx", "src/lib/release-contract.ts"],
  "4.10": ["src/lib/report-export.ts", "src/lib/export-job-visibility.ts", "src/lib/semantics.test.ts"],
  "4.11": ["src/lib/release-contract.ts", "src/lib/product-surface/feature-registry.ts", "src/lib/release-contract.test.ts"],
  "4.12": ["src/lib/advanced-assurance-continuity.ts", "src/lib/read-model-refresh.ts", "src/lib/continuity.test.ts"],
  "4.13": ["src/lib/governance.ts", "src/actions/product-surface-settings.ts", "src/lib/semantics.test.ts"],
  "4.14": ["src/lib/job-visibility.ts", "src/lib/import-job-visibility.ts", "src/lib/export-job-visibility.ts", "src/lib/semantics.test.ts"],
  "4.15": ["src/lib/product-telemetry.ts", "src/lib/release-contract.ts", "src/lib/objective-telemetry.test.ts"],
  "4.16": ["src/lib/report-export.ts", "src/lib/objective-measurements.test.ts"],
  "5": ["src/lib/read-models.ts", "src/lib/mutation-envelope.ts", "src/lib/data-contracts.test.ts", "supabase/migrations/057_v10_runtime_contracts.sql"],
  "5.1": ["src/lib/release-contract.ts", "src/lib/data-contracts.test.ts"],
  "5.2": ["src/lib/read-models.ts", "src/lib/data-contracts.test.ts"],
  "5.3": ["src/lib/read-models.ts", "src/lib/read-model-refresh.test.ts"],
  "5.4": ["src/lib/mutation-envelope.ts", "src/lib/semantics.test.ts"],
  "5.5": ["src/lib/server-contracts.ts", "src/lib/server-contracts.test.ts"],
  "5.6": ["src/lib/server-contracts.ts", "src/lib/server-contracts.test.ts"],
  "5.7": ["src/lib/mutation-envelope.ts", "src/lib/semantics.test.ts"],
  "6": ["src/lib/release-contract.ts", "src/lib/objective-measurements.test.ts"],
  "6.1": ["src/lib/activation-state.ts", "src/lib/semantics.test.ts"],
  "6.2": ["src/lib/work-semantics.ts", "src/lib/semantics.test.ts"],
  "6.3": ["src/lib/contract-health.ts", "src/lib/semantics.test.ts"],
  "6.4": ["src/lib/field-provenance.ts", "src/lib/semantics.test.ts"],
  "6.5": ["src/lib/renewal-posture.ts", "src/lib/semantics.test.ts"],
  "6.6": ["src/lib/evidence-collaboration.ts", "src/lib/semantics.test.ts"],
  "6.7": ["src/lib/approval-exception.ts", "src/lib/operational-contracts.test.ts"],
  "6.8": ["src/lib/route-api-catalog.ts", "src/lib/route-api-catalog.test.ts"],
  "6.9": ["src/lib/report-export.ts", "src/lib/semantics.test.ts"],
  "6.10": ["src/lib/governance.ts", "src/lib/semantics.test.ts"],
  "6.11": ["src/lib/job-visibility.ts", "src/lib/semantics.test.ts"],
  "6.12": ["src/lib/hardening-contracts.ts", "src/lib/hardening-contracts.test.ts"],
  "6.13": ["src/lib/ui-state-contracts.ts", "src/lib/ui-state-contracts.test.ts"],
  "6.14": ["src/lib/route-api-catalog.ts", "src/lib/route-api-catalog.test.ts"],
  "6.15": ["src/lib/read-models.ts", "src/lib/data-contracts.test.ts"],
  "6.16": ["src/lib/release-evidence.ts", "src/lib/release-evidence.test.ts"],
  "7": ["src/lib/release-contract.ts", "src/lib/release-contract.test.ts"],
  "8": ["src/lib/release-contract.ts", "src/lib/final-gap-audit.ts", "src/lib/final-gap-audit.test.ts"],
} as const;

// Version-name compatibility aliases. Prefer neutral exports in new code.
export { V10_SPEC_TRACE as SPEC_TRACE };
// End version-name compatibility aliases.
