export const V10_SPEC_TRACE: Record<string, readonly string[]> = {
  "1": ["src/lib/v10-release-contract.ts", "src/lib/v10-release-contract.v10.test.ts"],
  "2": ["src/lib/v10-release-contract.ts", "src/lib/v10-objective-measurements.v10.test.ts"],
  "2.1": ["src/lib/v10-objective-measurements.ts", "src/lib/v10-objective-measurements.v10.test.ts"],
  "2.2": ["src/lib/v10-release-evidence.ts", "src/lib/v10-release-evidence.v10.test.ts"],
  "3": ["src/lib/v10-release-contract.ts", "src/lib/v10-governance.ts", "src/lib/v10-hardening-contracts.v10.test.ts"],
  "3.1": ["src/lib/v10-release-contract.ts", "src/lib/v10-release-contract.v10.test.ts"],
  "3.1.1": ["src/lib/v10-readiness-scorecard.ts", "src/lib/v10-readiness-scorecard.v10.test.ts"],
  "3.2": ["src/lib/v10-work-semantics.ts", "src/lib/v10-semantics.v10.test.ts"],
  "3.3": ["src/lib/v10-contract-health.ts", "src/lib/v10-semantics.v10.test.ts"],
  "3.4": ["src/lib/v10-governance.ts", "src/lib/v10-semantics.v10.test.ts"],
  "3.5": ["src/lib/v10-hardening-contracts.ts", "src/lib/v10-hardening-contracts.v10.test.ts"],
  "4": ["src/lib/v10-ui-state-contracts.ts", "src/lib/v10-ui-state-contracts.v10.test.ts"],
  "4.1": ["src/lib/v10-activation-state.ts", "src/app/api/import/contracts/route.ts", "src/lib/v10-semantics.v10.test.ts"],
  "4.2": ["src/lib/v10-work-semantics.ts", "src/lib/work-hub-lens.ts", "src/app/(dashboard)/work/page.tsx", "src/lib/v10-semantics.v10.test.ts"],
  "4.3": ["src/app/(dashboard)/dashboard/page.tsx", "src/lib/v10-ui-state-contracts.ts", "src/lib/v10-ui-state-contracts.v10.test.ts"],
  "4.4": ["src/lib/v10-contract-health.ts", "src/lib/contract-detail-summary.ts", "src/lib/v10-semantics.v10.test.ts"],
  "4.5": ["src/lib/v10-field-provenance.ts", "src/lib/v10-release-contract.ts", "src/lib/v10-semantics.v10.test.ts"],
  "4.6": ["src/lib/v10-renewal-posture.ts", "src/lib/v10-semantics.v10.test.ts"],
  "4.7": ["src/lib/v10-evidence-collaboration.ts", "src/app/api/cron/v4/evidence-followup/route.ts", "src/lib/v10-semantics.v10.test.ts"],
  "4.8": ["src/lib/v10-approval-exception.ts", "src/actions/approvals.ts", "src/actions/exceptions.ts", "src/actions/tasks.ts", "src/lib/v10-operational-contracts.v10.test.ts"],
  "4.9": ["src/app/api/command-palette/contracts/route.ts", "src/components/layout/command-palette.tsx", "src/components/layout/command-palette.ui.test.tsx", "src/lib/v10-release-contract.ts"],
  "4.10": ["src/lib/v10-report-export.ts", "src/lib/export-job-visibility.ts", "src/lib/v10-semantics.v10.test.ts"],
  "4.11": ["src/lib/v10-release-contract.ts", "src/lib/product-surface/feature-registry.ts", "src/lib/v10-release-contract.v10.test.ts"],
  "4.12": ["src/lib/v10-advanced-assurance-continuity.ts", "src/lib/v10-read-model-refresh.ts", "src/lib/v10-continuity.v10.test.ts"],
  "4.13": ["src/lib/v10-governance.ts", "src/actions/product-surface-settings.ts", "src/lib/v10-semantics.v10.test.ts"],
  "4.14": ["src/lib/v10-job-visibility.ts", "src/lib/import-job-visibility.ts", "src/lib/export-job-visibility.ts", "src/lib/v10-semantics.v10.test.ts"],
  "4.15": ["src/lib/product-telemetry.ts", "src/lib/v10-release-contract.ts", "src/lib/v10-objective-telemetry.v10.test.ts"],
  "4.16": ["src/lib/v10-report-export.ts", "src/lib/v10-objective-measurements.v10.test.ts"],
  "5": ["src/lib/v10-read-models.ts", "src/lib/v10-mutation-envelope.ts", "src/lib/v10-data-contracts.v10.test.ts", "supabase/migrations/057_v10_runtime_contracts.sql"],
  "5.1": ["src/lib/v10-release-contract.ts", "src/lib/v10-data-contracts.v10.test.ts"],
  "5.2": ["src/lib/v10-read-models.ts", "src/lib/v10-data-contracts.v10.test.ts"],
  "5.3": ["src/lib/v10-read-models.ts", "src/lib/v10-read-model-refresh.v10.test.ts"],
  "5.4": ["src/lib/v10-mutation-envelope.ts", "src/lib/v10-semantics.v10.test.ts"],
  "5.5": ["src/lib/v10-server-contracts.ts", "src/lib/v10-server-contracts.v10.test.ts"],
  "5.6": ["src/lib/v10-server-contracts.ts", "src/lib/v10-server-contracts.v10.test.ts"],
  "5.7": ["src/lib/v10-mutation-envelope.ts", "src/lib/v10-semantics.v10.test.ts"],
  "6": ["src/lib/v10-release-contract.ts", "src/lib/v10-objective-measurements.v10.test.ts"],
  "6.1": ["src/lib/v10-activation-state.ts", "src/lib/v10-semantics.v10.test.ts"],
  "6.2": ["src/lib/v10-work-semantics.ts", "src/lib/v10-semantics.v10.test.ts"],
  "6.3": ["src/lib/v10-contract-health.ts", "src/lib/v10-semantics.v10.test.ts"],
  "6.4": ["src/lib/v10-field-provenance.ts", "src/lib/v10-semantics.v10.test.ts"],
  "6.5": ["src/lib/v10-renewal-posture.ts", "src/lib/v10-semantics.v10.test.ts"],
  "6.6": ["src/lib/v10-evidence-collaboration.ts", "src/lib/v10-semantics.v10.test.ts"],
  "6.7": ["src/lib/v10-approval-exception.ts", "src/lib/v10-operational-contracts.v10.test.ts"],
  "6.8": ["src/lib/v10-route-api-catalog.ts", "src/lib/v10-route-api-catalog.v10.test.ts"],
  "6.9": ["src/lib/v10-report-export.ts", "src/lib/v10-semantics.v10.test.ts"],
  "6.10": ["src/lib/v10-governance.ts", "src/lib/v10-semantics.v10.test.ts"],
  "6.11": ["src/lib/v10-job-visibility.ts", "src/lib/v10-semantics.v10.test.ts"],
  "6.12": ["src/lib/v10-hardening-contracts.ts", "src/lib/v10-hardening-contracts.v10.test.ts"],
  "6.13": ["src/lib/v10-ui-state-contracts.ts", "src/lib/v10-ui-state-contracts.v10.test.ts"],
  "6.14": ["src/lib/v10-route-api-catalog.ts", "src/lib/v10-route-api-catalog.v10.test.ts"],
  "6.15": ["src/lib/v10-read-models.ts", "src/lib/v10-data-contracts.v10.test.ts"],
  "6.16": ["src/lib/v10-release-evidence.ts", "src/lib/v10-release-evidence.v10.test.ts"],
  "7": ["src/lib/v10-release-contract.ts", "src/lib/v10-release-contract.v10.test.ts"],
  "8": ["src/lib/v10-release-contract.ts", "src/lib/v10-final-gap-audit.ts", "src/lib/v10-final-gap-audit.v10.test.ts"],
} as const;
