/**
 * Maps v9 spec ## section ids to ≥1 concrete repo path (Tier A trace matrix).
 * Generated/maintained for v9-spec-trace.v9.test.ts.
 */
export const V9_SPEC_TRACE: Record<string, readonly string[]> = {
  "1": [
    "src/lib/v9-meta-scope-s1-s6.v9.test.ts",
    "src/lib/v9-spec-principles.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "2": [
    "src/lib/v9-meta-scope-s1-s6.v9.test.ts",
    "src/lib/v9-spec-principles.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "3": [
    "src/lib/v9-meta-scope-s1-s6.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
    "src/app/(dashboard)/contracts/intake/page.tsx",
    "src/app/(dashboard)/more/page.tsx",
    "src/components/layout/command-palette-loader.tsx",
    "src/lib/v9-scope-constraints.v9.test.ts",
  ],
  "4": [
    "src/lib/v9-meta-scope-s1-s6.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "5": [
    "src/lib/v9-meta-scope-s1-s6.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "5.1": [
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "5.2": [
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "5.3": [
    "src/app/(dashboard)/layout.tsx",
    "src/lib/observability/log-redaction.ts",
    "src/lib/observability/sentry-scrub.ts",
    "src/lib/v9-pii-minimization.v9.test.ts",
    "src/lib/v9-dashboard-shell-auth.v9.test.ts",
    "src/lib/v9-dashboard-no-dangerous-html.v9.test.ts",
    "src/lib/v9-user-generated-content-surfaces.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/app/api/import-export-job-org-scope.v9.test.ts",
    "src/app/api/import-contracts-job-post-retry.v9.test.ts",
    "src/lib/v9-plan-enforcement-read-nav.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "5.4": [
    "src/lib/v9-forbidden-hidden-family-core.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "6": [
    "src/lib/v9-meta-scope-s1-s6.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "7": [
    "src/actions/onboarding-calibration.ts",
    "src/components/dashboard/onboarding-banner.tsx",
    "src/lib/v9-onboarding-banner-activation-path.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "7.1": [
    "src/actions/onboarding-calibration.ts",
    "src/components/dashboard/onboarding-banner.tsx",
    "src/lib/v9-onboarding-banner-activation-path.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "7.2": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/actions/onboarding-calibration.ts",
    "src/components/dashboard/onboarding-banner.tsx",
    "src/components/dashboard/onboarding-banner.ui.test.tsx",
    "src/lib/v9-onboarding-banner-activation-path.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "7.3": [
    "src/actions/onboarding-calibration.ts",
    "src/components/dashboard/onboarding-banner.tsx",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "7.4": [
    "src/actions/onboarding-calibration.ts",
    "src/components/dashboard/onboarding-banner.tsx",
    "src/lib/v9-onboarding-recovery-copy.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "7.5": [
    "src/actions/onboarding-calibration.ts",
    "src/components/dashboard/onboarding-banner.tsx",
    "src/lib/v9-onboarding-banner-activation-path.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "8": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/lib/v9-dashboard-home-composition.v9.test.ts",
    "src/lib/v9-plan-enforcement-read-nav.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "8.1": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/lib/v9-dashboard-home-composition.v9.test.ts",
    "src/lib/v9-dashboard-persona-density.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "8.2": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/lib/v9-dashboard-home-composition.v9.test.ts",
    "src/lib/v9-dashboard-persona-density.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "8.3": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/lib/v9-dashboard-home-composition.v9.test.ts",
    "src/lib/v9-dashboard-persona-density.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "8.4": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/lib/v9-dashboard-home-composition.v9.test.ts",
    "src/lib/v9-dashboard-persona-density.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "8.5": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/lib/v9-dashboard-home-composition.v9.test.ts",
    "src/lib/v9-deep-link-query-encoding.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "8.6": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/lib/v9-dashboard-home-composition.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "8.7": [
    "src/components/dashboard/dashboard-upper.tsx",
    "src/components/dashboard/dashboard-lower.tsx",
    "src/app/(dashboard)/layout.tsx",
    "src/components/layout/refetch-on-window-focus.tsx",
    "src/lib/v9-dashboard-home-composition.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "9": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/lib/v9-contracts-list-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "9.1": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/lib/v9-contracts-list-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "9.2": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/lib/v9-long-title-unicode-row.v9.test.ts",
    "src/lib/v9-contracts-list-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "9.3": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/components/contracts/contracts-saved-view-create-form.tsx",
    "src/lib/contract-filters.ts",
    "src/lib/contract-list-id-filters.ts",
    "src/lib/contract-list-id-filters.v9.test.ts",
    "src/lib/contracts-search-url.ts",
    "src/lib/v9-cmdk-contracts-search-parity.v9.test.ts",
    "src/lib/v9-renewal-horizon-contract-list-parity.v9.test.ts",
    "src/lib/v9-contracts-list-surface.v9.test.ts",
    "src/lib/v9-contracts-url-and-params.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "9.4": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/lib/v9-contracts-list-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "9.5": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/actions/contracts-lifecycle.ts",
    "src/lib/v9-contracts-lifecycle-surface.v9.test.ts",
    "src/lib/v9-contracts-list-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "9.6": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/lib/v9-contracts-list-surface.v9.test.ts",
    "src/lib/v9-virtualization-selection-invariants.v9.test.ts",
    "src/lib/v9-list-virtualization-contract-table.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "10": [
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/v9-detail-page-fold-proxy.v9.test.ts",
    "src/lib/contracts-subroutes-not-found-matrix.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "10.1": [
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/v9-detail-page-fold-proxy.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "10.2": [
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/v9-detail-page-fold-proxy.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "10.3": [
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/v9-detail-page-fold-proxy.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "10.4": [
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/actions/contracts-lifecycle.ts",
    "src/lib/v9-contracts-lifecycle-surface.v9.test.ts",
    "src/lib/v9-detail-page-fold-proxy.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "10.5": [
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/v9-detail-page-fold-proxy.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "10.6": [
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/v9-data-freshness.ts",
    "src/lib/v9-detail-page-fold-proxy.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "11": [
    "src/components/contracts/field-review.tsx",
    "src/app/(dashboard)/contracts/review/page.tsx",
    "src/lib/v9-review-queue-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "11.1": [
    "src/components/contracts/field-review.tsx",
    "src/app/(dashboard)/contracts/review/page.tsx",
    "src/lib/v9-review-queue-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "11.2": [
    "src/components/contracts/field-review.tsx",
    "src/components/contracts/field-review.ui.test.tsx",
    "src/app/(dashboard)/contracts/review/page.tsx",
    "src/lib/v9-review-queue-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "11.3": [
    "src/components/contracts/field-review.tsx",
    "src/components/contracts/field-review.ui.test.tsx",
    "src/app/(dashboard)/contracts/review/page.tsx",
    "src/lib/v9-review-queue-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "11.4": [
    "src/components/contracts/field-review.tsx",
    "src/app/(dashboard)/contracts/review/page.tsx",
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/review-save-next-telemetry-link.tsx",
    "src/lib/v9-review-queue-surface.v9.test.ts",
    "src/lib/v9-v4-execution-engine-bridge.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "11.5": [
    "src/components/contracts/field-review.tsx",
    "src/app/(dashboard)/contracts/review/page.tsx",
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/components/contracts/review-save-next-telemetry-link.tsx",
    "src/lib/v9-review-queue-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "12": [
    "src/app/(dashboard)/work/page.tsx",
    "src/components/ui/permission-eligibility-hint.tsx",
    "src/components/work/work-queue-inline-actions.tsx",
    "src/components/work/work-queue-inline-actions-gate.tsx",
    "src/lib/v9-work-queue-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "12.1": [
    "src/app/(dashboard)/work/page.tsx",
    "src/components/ui/permission-eligibility-hint.tsx",
    "src/components/work/work-queue-inline-actions.tsx",
    "src/components/work/work-queue-inline-actions-gate.tsx",
    "src/lib/v9-work-queue-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "12.2": [
    "src/app/(dashboard)/work/page.tsx",
    "src/lib/v9-work-lens-empty-states.v9.test.ts",
    "src/lib/v9-business-dates.ts",
    "src/lib/v9-business-dates-drift.v9.test.ts",
    "src/components/ui/permission-eligibility-hint.tsx",
    "src/components/work/work-queue-inline-actions.tsx",
    "src/components/work/work-queue-inline-actions-gate.tsx",
    "src/lib/v9-work-queue-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "12.3": [
    "src/app/(dashboard)/work/page.tsx",
    "src/components/ui/permission-eligibility-hint.tsx",
    "src/components/work/work-queue-inline-actions.tsx",
    "src/components/work/work-queue-inline-actions-gate.tsx",
    "src/lib/v9-permission-eligibility-work-queue.v9.test.ts",
    "src/lib/v9-tasks-obligations-distinct-language.v9.test.ts",
    "src/lib/v9-work-queue-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "12.4": [
    "src/app/(dashboard)/work/page.tsx",
    "src/components/ui/permission-eligibility-hint.tsx",
    "src/components/work/work-queue-inline-actions.tsx",
    "src/components/work/work-queue-inline-actions-gate.tsx",
    "src/lib/v9-work-queue-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "12.5": [
    "src/app/(dashboard)/work/page.tsx",
    "src/components/ui/permission-eligibility-hint.tsx",
    "src/components/work/work-queue-inline-actions.tsx",
    "src/components/work/work-queue-inline-actions.ui.test.tsx",
    "src/components/work/work-queue-inline-actions-gate.tsx",
    "src/lib/v9-tasks-obligations-distinct-language.v9.test.ts",
    "src/lib/v9-work-queue-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "13": [
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/components/contracts/renewal-row-checklist-actions.tsx",
    "src/lib/v9-renewals-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "13.1": [
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/components/contracts/renewal-row-checklist-actions.tsx",
    "src/lib/v9-renewals-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "13.2": [
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/lib/v9-sparse-records.ts",
    "src/lib/v9-sparse-records.v9.test.ts",
    "src/components/contracts/renewal-row-checklist-actions.tsx",
    "src/lib/v9-renewals-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "13.3": [
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/components/contracts/renewal-row-checklist-actions.tsx",
    "src/lib/contract-filters.ts",
    "src/lib/v9-renewal-horizon-contract-list-parity.v9.test.ts",
    "src/lib/renewal-next-action.ts",
    "src/lib/renewal-next-action.v9.test.ts",
    "src/lib/v9-renewals-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "13.4": [
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/components/contracts/renewal-row-checklist-actions.tsx",
    "src/lib/v9-renewals-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "13.5": [
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/components/contracts/renewal-row-checklist-actions.tsx",
    "src/lib/v9-renewals-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "14": [
    "src/app/(dashboard)/contracts/exceptions/page.tsx",
    "src/actions/exceptions.ts",
    "src/components/contracts/exception-mutation-panels.tsx",
    "src/lib/v9-exceptions-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "14.1": [
    "src/app/(dashboard)/contracts/exceptions/page.tsx",
    "src/actions/exceptions.ts",
    "src/components/contracts/exception-mutation-panels.tsx",
    "src/lib/v9-exceptions-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "14.2": [
    "src/app/(dashboard)/contracts/exceptions/page.tsx",
    "src/actions/exceptions.ts",
    "src/components/contracts/exception-mutation-panels.tsx",
    "src/lib/v9-exceptions-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "14.3": [
    "src/app/(dashboard)/contracts/exceptions/page.tsx",
    "src/actions/exceptions.ts",
    "src/lib/exception-priority.ts",
    "src/lib/v9-exceptions-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "14.4": [
    "src/app/(dashboard)/contracts/exceptions/page.tsx",
    "src/actions/exceptions.ts",
    "src/components/contracts/exception-mutation-panels.tsx",
    "src/lib/v9-exceptions-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "14.5": [
    "src/app/(dashboard)/contracts/exceptions/page.tsx",
    "src/actions/exceptions.ts",
    "src/lib/v9-exception-audit-trail-nonclutter.v9.test.ts",
    "src/lib/v9-exceptions-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "15": [
    "src/app/(dashboard)/contracts/evidence-studio/page.tsx",
    "src/lib/evidence-display.ts",
    "src/lib/evidence-display.v9.test.ts",
    "src/app/api/evidence/[id]/[action]/route.ts",
    "src/lib/v9-api-critical-routes-matrix.v9.test.ts",
    "src/lib/v9-evidence-studio-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "15.1": [
    "src/app/(dashboard)/contracts/evidence-studio/page.tsx",
    "src/app/api/evidence/[id]/[action]/route.ts",
    "src/lib/v9-evidence-studio-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "15.2": [
    "src/app/(dashboard)/contracts/evidence-studio/page.tsx",
    "src/lib/evidence-display.ts",
    "src/lib/evidence-display.v9.test.ts",
    "src/app/api/evidence/[id]/[action]/route.ts",
    "src/lib/v9-evidence-studio-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "15.3": [
    "src/app/(dashboard)/contracts/evidence-studio/page.tsx",
    "src/components/contracts/evidence-submission-form.tsx",
    "src/app/api/evidence/[id]/[action]/route.ts",
    "src/lib/v9-evidence-studio-surface.v9.test.ts",
    "src/lib/v9-form-preserve-on-reject.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "15.4": [
    "src/app/(dashboard)/contracts/evidence-studio/page.tsx",
    "src/lib/evidence-display.ts",
    "src/lib/evidence-display.v9.test.ts",
    "src/components/contracts/contract-evidence-requirements-panel.tsx",
    "src/components/contracts/contract-evidence-requirements-panel.ui.test.tsx",
    "src/app/api/evidence/[id]/[action]/route.ts",
    "src/lib/v9-evidence-studio-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "15.5": [
    "src/app/(dashboard)/contracts/evidence-studio/page.tsx",
    "src/components/contracts/evidence-submission-review-actions.tsx",
    "src/app/api/evidence/[id]/[action]/route.ts",
    "src/lib/v9-evidence-studio-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "16": [
    "src/components/layout/command-palette.tsx",
    "src/lib/product-surface/cmdk-search-jumps.ts",
    "src/lib/v9-search-cmdk-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "16.1": [
    "src/components/layout/command-palette.tsx",
    "src/lib/product-surface/cmdk-search-jumps.ts",
    "src/lib/contracts-search-url.ts",
    "src/lib/v9-cmdk-contracts-search-parity.v9.test.ts",
    "src/lib/v9-deep-link-query-encoding.v9.test.ts",
    "src/lib/v9-search-cmdk-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "16.2": [
    "src/components/layout/command-palette.tsx",
    "e2e/v9-core-smoke.spec.ts",
    "src/lib/product-surface/cmdk-search-jumps.ts",
    "src/lib/product-surface/cmdk-search-jumps.test.ts",
    "src/lib/v9-search-cmdk-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "16.3": [
    "src/components/layout/command-palette.tsx",
    "e2e/v9-core-smoke.spec.ts",
    "src/lib/product-surface/cmdk-search-jumps.ts",
    "src/lib/v9-search-cmdk-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "16.4": [
    "src/components/layout/command-palette.tsx",
    "e2e/v9-core-smoke.spec.ts",
    "src/lib/product-surface/cmdk-search-jumps.ts",
    "src/lib/v9-search-cmdk-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "16.5": [
    "src/components/layout/command-palette.tsx",
    "src/lib/product-surface/cmdk-search-jumps.ts",
    "src/lib/v9-search-cmdk-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "17": [
    "src/lib/import-jobs.ts",
    "src/lib/extraction/run-pipeline.ts",
    "src/app/api/import/contracts/[jobId]/route.ts",
    "src/lib/v9-api-critical-routes-matrix.v9.test.ts",
    "src/lib/v9-import-export-surfaces.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "17.1": [
    "src/lib/import-jobs.ts",
    "src/lib/extraction/run-pipeline.ts",
    "src/app/api/import/contracts/[jobId]/route.ts",
    "src/lib/v9-import-export-surfaces.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "17.2": [
    "src/lib/import-jobs.ts",
    "src/lib/extraction/run-pipeline.ts",
    "src/app/api/import/contracts/[jobId]/route.ts",
    "src/components/contracts/import-job-retry-button.tsx",
    "src/components/contracts/import-job-retry-button.ui.test.tsx",
    "src/lib/v9-import-export-surfaces.v9.test.ts",
    "src/lib/v9-upload-import-http-error-copy.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "17.3": [
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/import-jobs.ts",
    "src/lib/extraction/run-pipeline.ts",
    "src/app/api/import/contracts/[jobId]/route.ts",
    "src/lib/v9-import-export-surfaces.v9.test.ts",
    "src/lib/v9-extraction-job-alert-states.v9.test.ts",
    "src/lib/v9-extraction-queued-vs-in-progress-ui.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "17.4": [
    "src/lib/import-job-visibility.ts",
    "src/lib/import-job-visibility.v9.test.ts",
    "src/lib/v9-outcome-semantics.ts",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/lib/import-jobs.ts",
    "src/lib/extraction/run-pipeline.ts",
    "src/app/api/import/contracts/[jobId]/route.ts",
    "src/lib/v9-import-export-surfaces.v9.test.ts",
    "src/lib/v9-extraction-job-alert-states.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "17.5": [
    "src/lib/import-jobs.ts",
    "src/lib/extraction/run-pipeline.ts",
    "src/app/api/import/contracts/[jobId]/route.ts",
    "src/lib/v9-import-export-surfaces.v9.test.ts",
    "src/lib/v9-supabase-050-read-write-ui.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "18": [
    "src/lib/notification-delivery.ts",
    "src/lib/reminder-delivery-visibility.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "18.1": [
    "src/lib/notification-delivery.ts",
    "src/lib/reminder-delivery-visibility.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "18.2": [
    "src/lib/notification-delivery.ts",
    "src/lib/reminder-delivery-visibility.ts",
    "src/lib/in-app-notification-display.ts",
    "src/lib/v9-notification-deeplink-matrix.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "18.3": [
    "src/lib/notification-delivery.ts",
    "src/lib/reminder-delivery-visibility.ts",
    "src/lib/notification-internal-deeplink.ts",
    "src/lib/product-surface/cmdk-search-jumps.ts",
    "src/app/(dashboard)/contracts/collaboration/page.tsx",
    "src/lib/v9-notification-deeplink-matrix.v9.test.ts",
    "src/lib/v9-deep-link-query-encoding.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "18.4": [
    "src/lib/notification-delivery.ts",
    "src/lib/reminder-delivery-visibility.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "18.5": [
    "src/lib/notification-delivery.ts",
    "src/lib/reminder-delivery-visibility.ts",
    "src/lib/in-app-notification-display.ts",
    "src/lib/in-app-notification-display.v9.test.ts",
    "src/app/(dashboard)/contracts/collaboration/page.tsx",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "19": [
    "src/app/(dashboard)/reports/page.tsx",
    "src/app/api/export/contracts/route.ts",
    "src/lib/v9-api-critical-routes-matrix.v9.test.ts",
    "src/lib/v9-import-export-surfaces.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "19.1": [
    "src/app/(dashboard)/reports/page.tsx",
    "src/app/api/export/contracts/route.ts",
    "src/lib/v9-import-export-surfaces.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "19.2": [
    "src/app/(dashboard)/reports/page.tsx",
    "src/app/api/export/contracts/route.ts",
    "src/lib/v9-import-export-surfaces.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "19.3": [
    "src/lib/export-job-visibility.ts",
    "src/lib/export-job-visibility.v9.test.ts",
    "src/lib/v9-outcome-semantics.ts",
    "src/app/(dashboard)/reports/page.tsx",
    "src/app/api/export/contracts/route.ts",
    "src/app/api/export/review-packet/route.ts",
    "src/lib/csv-formula-safe.ts",
    "src/lib/csv-formula-safe.v9.test.ts",
    "src/lib/v9-import-export-surfaces.v9.test.ts",
    "src/lib/v9-export-csv-workspace-gate.v9.test.ts",
    "src/lib/v9-supabase-050-read-write-ui.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "19.4": [
    "src/app/(dashboard)/reports/page.tsx",
    "src/app/api/export/contracts/route.ts",
    "src/lib/export-contract-csv-field-policy.ts",
    "src/lib/v9-import-export-surfaces.v9.test.ts",
    "src/lib/v9-export-csv-workspace-gate.v9.test.ts",
    "src/lib/v9-export-csv-core-column-suppression.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "20": [
    "src/components/ui/empty-state.tsx",
    "src/lib/v9-empty-state-prohibitions.v9.test.ts",
    "src/lib/v9-empty-states-high-traffic.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "20.1": [
    "src/lib/v9-work-lens-empty-states.v9.test.ts",
    "src/components/ui/empty-state.tsx",
    "src/lib/v9-empty-state-prohibitions.v9.test.ts",
    "src/lib/v9-empty-states-high-traffic.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "20.2": [
    "src/components/ui/empty-state.tsx",
    "src/lib/v9-empty-state-prohibitions.v9.test.ts",
    "src/lib/v9-empty-states-high-traffic.v9.test.ts",
    "src/lib/v9-empty-state-cta-primitive.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "20.3": [
    "src/lib/v9-forbidden-hidden-family-core.v9.test.ts",
    "src/components/ui/empty-state.tsx",
    "src/lib/v9-empty-state-prohibitions.v9.test.ts",
    "src/lib/v9-empty-states-high-traffic.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "21": [
    "src/app/(dashboard)/loading-error-consistency.v9.test.ts",
    "src/lib/v9-mutation-feedback-surface.v9.test.ts",
    "src/lib/v9-coverage-inventory.v9.test.ts",
    "src/app/(dashboard)/loading.tsx",
    "src/app/(dashboard)/dashboard/loading.tsx",
    "src/app/(dashboard)/contracts/loading.tsx",
    "src/app/(dashboard)/reports/loading.tsx",
    "src/app/(dashboard)/settings/loading.tsx",
    "src/app/(dashboard)/assurance/loading.tsx",
    "src/app/(dashboard)/decisions/loading.tsx",
    "src/app/(dashboard)/dashboard/persona/loading.tsx",
    "src/app/(dashboard)/onboarding/calibration/loading.tsx",
    "src/app/(dashboard)/contracts/analytics/loading.tsx",
    "src/app/(dashboard)/contracts/tasks/loading.tsx",
    "src/app/(dashboard)/contracts/reports/loading.tsx",
    "src/app/(dashboard)/contracts/data-quality/loading.tsx",
    "src/app/(dashboard)/contracts/[id]/loading.tsx",
    "src/app/(dashboard)/work/loading.tsx",
    "src/app/(dashboard)/contracts/renewals/loading.tsx",
    "src/app/(dashboard)/contracts/exceptions/loading.tsx",
    "src/app/(dashboard)/contracts/evidence-studio/loading.tsx",
    "src/app/(dashboard)/contracts/review/loading.tsx",
    "src/app/(dashboard)/contracts/bulk/loading.tsx",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "21.1": [
    "src/app/(dashboard)/loading-error-consistency.v9.test.ts",
    "src/lib/v9-mutation-feedback-surface.v9.test.ts",
    "src/lib/v9-coverage-inventory.v9.test.ts",
    "src/app/(dashboard)/loading.tsx",
    "src/app/(dashboard)/dashboard/loading.tsx",
    "src/app/(dashboard)/contracts/loading.tsx",
    "src/app/(dashboard)/reports/loading.tsx",
    "src/app/(dashboard)/settings/loading.tsx",
    "src/app/(dashboard)/assurance/loading.tsx",
    "src/app/(dashboard)/decisions/loading.tsx",
    "src/app/(dashboard)/dashboard/persona/loading.tsx",
    "src/app/(dashboard)/onboarding/calibration/loading.tsx",
    "src/app/(dashboard)/contracts/analytics/loading.tsx",
    "src/app/(dashboard)/contracts/tasks/loading.tsx",
    "src/app/(dashboard)/contracts/reports/loading.tsx",
    "src/app/(dashboard)/contracts/data-quality/loading.tsx",
    "src/app/(dashboard)/contracts/[id]/loading.tsx",
    "src/app/(dashboard)/work/loading.tsx",
    "src/app/(dashboard)/contracts/renewals/loading.tsx",
    "src/app/(dashboard)/contracts/exceptions/loading.tsx",
    "src/app/(dashboard)/contracts/evidence-studio/loading.tsx",
    "src/app/(dashboard)/contracts/review/loading.tsx",
    "src/app/(dashboard)/contracts/bulk/loading.tsx",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "21.2": [
    "src/app/(dashboard)/loading-error-consistency.v9.test.ts",
    "src/lib/v9-mutation-feedback-surface.v9.test.ts",
    "src/lib/v9-coverage-inventory.v9.test.ts",
    "src/app/(dashboard)/loading.tsx",
    "src/app/(dashboard)/dashboard/loading.tsx",
    "src/app/(dashboard)/contracts/loading.tsx",
    "src/app/(dashboard)/reports/loading.tsx",
    "src/app/(dashboard)/settings/loading.tsx",
    "src/app/(dashboard)/assurance/loading.tsx",
    "src/app/(dashboard)/decisions/loading.tsx",
    "src/app/(dashboard)/dashboard/persona/loading.tsx",
    "src/app/(dashboard)/onboarding/calibration/loading.tsx",
    "src/app/(dashboard)/contracts/analytics/loading.tsx",
    "src/app/(dashboard)/contracts/tasks/loading.tsx",
    "src/app/(dashboard)/contracts/reports/loading.tsx",
    "src/app/(dashboard)/contracts/data-quality/loading.tsx",
    "src/app/(dashboard)/contracts/[id]/loading.tsx",
    "src/app/(dashboard)/work/loading.tsx",
    "src/app/(dashboard)/contracts/renewals/loading.tsx",
    "src/app/(dashboard)/contracts/exceptions/loading.tsx",
    "src/app/(dashboard)/contracts/evidence-studio/loading.tsx",
    "src/app/(dashboard)/contracts/review/loading.tsx",
    "src/app/(dashboard)/contracts/bulk/loading.tsx",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "21.3": [
    "src/app/(dashboard)/loading-error-consistency.v9.test.ts",
    "src/lib/v9-mutation-feedback-surface.v9.test.ts",
    "src/lib/v9-optimistic-mutation-inventory.v9.test.ts",
    "src/lib/v9-coverage-inventory.v9.test.ts",
    "src/app/(dashboard)/loading.tsx",
    "src/app/(dashboard)/dashboard/loading.tsx",
    "src/app/(dashboard)/contracts/loading.tsx",
    "src/app/(dashboard)/reports/loading.tsx",
    "src/app/(dashboard)/settings/loading.tsx",
    "src/app/(dashboard)/assurance/loading.tsx",
    "src/app/(dashboard)/decisions/loading.tsx",
    "src/app/(dashboard)/dashboard/persona/loading.tsx",
    "src/app/(dashboard)/onboarding/calibration/loading.tsx",
    "src/app/(dashboard)/contracts/analytics/loading.tsx",
    "src/app/(dashboard)/contracts/tasks/loading.tsx",
    "src/app/(dashboard)/contracts/reports/loading.tsx",
    "src/app/(dashboard)/contracts/data-quality/loading.tsx",
    "src/app/(dashboard)/contracts/[id]/loading.tsx",
    "src/app/(dashboard)/work/loading.tsx",
    "src/app/(dashboard)/contracts/renewals/loading.tsx",
    "src/app/(dashboard)/contracts/exceptions/loading.tsx",
    "src/app/(dashboard)/contracts/evidence-studio/loading.tsx",
    "src/app/(dashboard)/contracts/review/loading.tsx",
    "src/app/(dashboard)/contracts/bulk/loading.tsx",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "21.4": [
    "src/app/(dashboard)/loading-error-consistency.v9.test.ts",
    "src/lib/v9-revalidate-cache-stability.v9.test.ts",
    "src/lib/v9-mutation-feedback-surface.v9.test.ts",
    "src/lib/v9-coverage-inventory.v9.test.ts",
    "src/app/(dashboard)/loading.tsx",
    "src/app/(dashboard)/dashboard/loading.tsx",
    "src/app/(dashboard)/contracts/loading.tsx",
    "src/app/(dashboard)/reports/loading.tsx",
    "src/app/(dashboard)/settings/loading.tsx",
    "src/app/(dashboard)/assurance/loading.tsx",
    "src/app/(dashboard)/decisions/loading.tsx",
    "src/app/(dashboard)/dashboard/persona/loading.tsx",
    "src/app/(dashboard)/onboarding/calibration/loading.tsx",
    "src/app/(dashboard)/contracts/analytics/loading.tsx",
    "src/app/(dashboard)/contracts/tasks/loading.tsx",
    "src/app/(dashboard)/contracts/reports/loading.tsx",
    "src/app/(dashboard)/contracts/data-quality/loading.tsx",
    "src/app/(dashboard)/contracts/[id]/loading.tsx",
    "src/app/(dashboard)/work/loading.tsx",
    "src/app/(dashboard)/contracts/renewals/loading.tsx",
    "src/app/(dashboard)/contracts/exceptions/loading.tsx",
    "src/app/(dashboard)/contracts/evidence-studio/loading.tsx",
    "src/app/(dashboard)/contracts/review/loading.tsx",
    "src/app/(dashboard)/contracts/bulk/loading.tsx",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "22": [
    "src/lib/recoverable-mutation-error.ts",
    "src/lib/v9-api-client-errors.ts",
    "src/app/(dashboard)/error.tsx",
    "src/app/(marketing)/error.tsx",
    "src/lib/v9-errors-recovery-surface.v9.test.ts",
    "src/lib/v9-client-exception-capture.v9.test.ts",
    "src/lib/contracts-subroutes-not-found-matrix.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "22.1": [
    "src/lib/recoverable-mutation-error.ts",
    "src/lib/v9-api-client-errors.ts",
    "src/lib/v9-api-client-errors.v9.test.ts",
    "src/app/(dashboard)/error.tsx",
    "src/app/(marketing)/error.tsx",
    "src/lib/v9-errors-recovery-surface.v9.test.ts",
    "src/lib/v9-client-exception-capture.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "22.2": [
    "src/lib/recoverable-mutation-error.ts",
    "src/lib/v9-api-client-errors.ts",
    "src/app/(dashboard)/error.tsx",
    "src/app/(marketing)/error.tsx",
    "src/lib/v9-errors-recovery-surface.v9.test.ts",
    "src/lib/v9-form-preserve-on-reject.v9.test.ts",
    "src/lib/v9-client-exception-capture.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "22.3": [
    "src/lib/recoverable-mutation-error.ts",
    "src/lib/v9-api-client-errors.ts",
    "src/app/(dashboard)/error.tsx",
    "src/app/(marketing)/error.tsx",
    "src/lib/v9-errors-recovery-surface.v9.test.ts",
    "src/lib/v9-client-exception-capture.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "22.4": [
    "src/lib/recoverable-mutation-error.ts",
    "src/lib/v9-api-client-errors.ts",
    "src/app/(dashboard)/error.tsx",
    "src/app/(marketing)/error.tsx",
    "src/lib/v9-errors-recovery-surface.v9.test.ts",
    "src/lib/v9-client-exception-capture.v9.test.ts",
    "src/lib/v9-dashboard-no-dangerous-html.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "23": [
    "src/components/layout/v9-page-load-reporter.tsx",
    "src/actions/product-telemetry.ts",
    "src/lib/v9-performance-page-load-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "23.1": [
    "src/components/layout/v9-page-load-reporter.tsx",
    "src/actions/product-telemetry.ts",
    "src/lib/v9-performance-page-load-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "23.2": [
    "src/components/layout/v9-page-load-reporter.tsx",
    "src/actions/product-telemetry.ts",
    "src/lib/v9-performance-page-load-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "23.3": [
    "src/components/layout/v9-page-load-reporter.tsx",
    "src/actions/product-telemetry.ts",
    "src/lib/v9-performance-page-load-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "23.4": [
    "src/components/layout/v9-page-load-reporter.tsx",
    "src/actions/product-telemetry.ts",
    "src/lib/v9-performance-page-load-surface.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "24": [
    "src/lib/navigation.ts",
    "src/lib/contracts.ts",
    "src/lib/contract-list.ts",
    "src/lib/v9-business-dates.ts",
    "src/lib/v9-timezone-date-format-sweep.v9.test.ts",
    "src/lib/v9-consistency-vocabulary-core.v9.test.ts",
    "src/lib/v9-route-metadata-core-anchors.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "24.1": [
    "src/lib/navigation.ts",
    "src/lib/contracts.ts",
    "src/lib/contract-list.ts",
    "src/lib/v9-consistency-vocabulary-core.v9.test.ts",
    "src/lib/v9-review-cadence-vs-queue-labels.v9.test.ts",
    "src/lib/v9-route-metadata-core-anchors.v9.test.ts",
    "src/lib/v9-tasks-obligations-distinct-language.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "24.2": [
    "src/lib/navigation.ts",
    "src/lib/contracts.ts",
    "src/lib/contract-list.ts",
    "src/lib/v9-consistency-vocabulary-core.v9.test.ts",
    "src/lib/v9-tasks-obligations-distinct-language.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "24.3": [
    "src/lib/navigation.ts",
    "src/lib/contracts.ts",
    "src/lib/contract-list.ts",
    "src/app/(dashboard)/contracts/watchlists/page.tsx",
    "src/lib/v9-consistency-vocabulary-core.v9.test.ts",
    "src/lib/v9-cross-surface-contract-status-labels.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "24.4": [
    "src/lib/navigation.ts",
    "src/lib/contracts.ts",
    "src/lib/contract-list.ts",
    "src/app/(dashboard)/contracts/page.tsx",
    "src/app/(dashboard)/contracts/watchlists/page.tsx",
    "src/lib/v9-consistency-vocabulary-core.v9.test.ts",
    "src/lib/v9-route-metadata-core-anchors.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "24.5": [
    "src/lib/navigation.ts",
    "src/lib/contracts.ts",
    "src/lib/contract-list.ts",
    "src/lib/v9-consistency-vocabulary-core.v9.test.ts",
    "src/lib/v9-route-metadata-core-anchors.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "25": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/app/(dashboard)/contracts/tasks/page.tsx",
    "src/app/(dashboard)/contracts/obligations/page.tsx",
    "src/app/(dashboard)/contracts/watchlists/page.tsx",
    "src/lib/v9-contract-table-a11y-responsive.v9.test.ts",
    "src/lib/v9-workspace-tables-scroll.v9.test.ts",
    "src/components/layout/command-palette.ui.test.tsx",
    "e2e/a11y.keyboard.spec.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "25.1": [
    "src/app/layout.tsx",
    "src/components/layout/skip-link.tsx",
    "src/app/(dashboard)/layout.tsx",
    "src/lib/v9-skip-link-landmarks.v9.test.ts",
    "src/components/contracts/contract-table.tsx",
    "src/lib/v9-contract-table-a11y-responsive.v9.test.ts",
    "src/components/layout/command-palette.ui.test.tsx",
    "e2e/a11y.keyboard.spec.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "25.2": [
    "src/components/contracts/contract-table.tsx",
    "src/lib/v9-contract-table-a11y-responsive.v9.test.ts",
    "src/components/layout/command-palette.ui.test.tsx",
    "e2e/a11y.keyboard.spec.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "25.3": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/app/(dashboard)/contracts/tasks/page.tsx",
    "src/app/(dashboard)/contracts/obligations/page.tsx",
    "src/app/(dashboard)/contracts/watchlists/page.tsx",
    "src/lib/v9-contract-table-a11y-responsive.v9.test.ts",
    "src/lib/v9-workspace-tables-scroll.v9.test.ts",
    "src/components/layout/command-palette.ui.test.tsx",
    "e2e/a11y.keyboard.spec.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "26": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/app/(dashboard)/contracts/tasks/page.tsx",
    "src/app/(dashboard)/contracts/obligations/page.tsx",
    "src/app/(dashboard)/contracts/watchlists/page.tsx",
    "src/lib/v9-contract-table-a11y-responsive.v9.test.ts",
    "src/lib/v9-workspace-tables-scroll.v9.test.ts",
    "src/app/(dashboard)/layout.tsx",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "26.1": [
    "src/components/contracts/contract-table.tsx",
    "src/lib/v9-contract-table-a11y-responsive.v9.test.ts",
    "src/app/(dashboard)/layout.tsx",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "26.2": [
    "src/components/contracts/contract-table.tsx",
    "src/lib/v9-long-title-unicode-row.v9.test.ts",
    "src/lib/v9-contract-table-a11y-responsive.v9.test.ts",
    "src/app/(dashboard)/layout.tsx",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "26.3": [
    "src/components/contracts/contract-table.tsx",
    "src/app/(dashboard)/contracts/renewals/page.tsx",
    "src/app/(dashboard)/contracts/tasks/page.tsx",
    "src/app/(dashboard)/contracts/obligations/page.tsx",
    "src/app/(dashboard)/contracts/watchlists/page.tsx",
    "src/lib/v9-contract-table-a11y-responsive.v9.test.ts",
    "src/lib/v9-workspace-tables-scroll.v9.test.ts",
    "src/app/(dashboard)/layout.tsx",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "27": [
    "src/lib/v9-data-freshness.ts",
    "src/lib/v9-job-lifecycle-copy.ts",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/app/(dashboard)/settings/health/page.tsx",
    "src/lib/v9-reliability-states-27-2.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "27.1": [
    "src/lib/v9-data-freshness.ts",
    "src/lib/v9-job-lifecycle-copy.ts",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/app/(dashboard)/settings/health/page.tsx",
    "src/lib/v9-reliability-states-27-2.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "27.2": [
    "src/lib/v9-data-freshness.ts",
    "src/lib/v9-job-lifecycle-copy.ts",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/app/(dashboard)/settings/health/page.tsx",
    "src/lib/reminder-delivery-visibility.ts",
    "src/lib/reminder-inactive-missing-dates-copy.v9.test.ts",
    "src/app/(dashboard)/contracts/[id]/page.tsx",
    "src/lib/v9-supabase-050-read-write-ui.v9.test.ts",
    "src/app/(dashboard)/reports/page.tsx",
    "src/app/(dashboard)/reports/reports-control-room-reliability.v9.test.ts",
    "src/lib/v9-reliability-states-27-2.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "27.3": [
    "src/lib/v9-data-freshness.ts",
    "src/lib/v9-job-lifecycle-copy.ts",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/app/(dashboard)/settings/health/page.tsx",
    "src/lib/v9-reliability-states-27-2.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "27.4": [
    "src/lib/v9-data-freshness.ts",
    "src/lib/v9-job-lifecycle-copy.ts",
    "src/components/contracts/extraction-job-alert.tsx",
    "src/app/(dashboard)/settings/health/page.tsx",
    "src/lib/v9-reliability-states-27-2.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "28": [
    "src/lib/product-telemetry.ts",
    "src/lib/product-telemetry.details.v9.test.ts",
    "src/lib/observability/log-redaction.ts",
    "src/lib/v9-pii-minimization.v9.test.ts",
    "src/lib/product-telemetry.wiring.v9.test.ts",
    "src/lib/v9-telemetry-tier-c-paths.v9.test.ts",
    "src/lib/v9-product-telemetry-swallow-errors.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "28.1": [
    "src/lib/product-telemetry.ts",
    "src/lib/product-telemetry.wiring.v9.test.ts",
    "src/lib/v9-telemetry-tier-c-paths.v9.test.ts",
    "src/lib/v9-product-telemetry-swallow-errors.v9.test.ts",
    "src/lib/v9-product-telemetry-client-nonblocking.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "28.2": [
    "src/lib/v9-metric-definitions.ts",
    "src/lib/v9-metric-definitions.v9.test.ts",
    "src/lib/product-telemetry.ts",
    "src/lib/product-telemetry.wiring.v9.test.ts",
    "src/lib/v9-telemetry-tier-c-paths.v9.test.ts",
    "src/lib/v9-product-telemetry-swallow-errors.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "28.3": [
    "src/actions/onboarding-calibration.ts",
    "src/lib/product-telemetry.ts",
    "src/lib/product-telemetry.wiring.v9.test.ts",
    "src/lib/v9-auditability-actions-28-3.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "29": [
    "src/lib/v9-plan-enforcement-bundles.v9.test.ts",
    "src/lib/v9-appendix-verbatim-anchors.v9.test.ts",
    "src/lib/v9-regression-bridge.v9.test.ts",
    "src/lib/v9-regression-acceptance-anchors.v9.test.ts",
    "src/lib/v9-coverage-inventory.v9.test.ts",
    "src/lib/v9-acceptance-criteria.test.ts",
    "src/lib/v9-acceptance-scripts-sync.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "29.1": [
    "src/lib/v9-plan-enforcement-bundles.v9.test.ts",
    "src/lib/v9-appendix-verbatim-anchors.v9.test.ts",
    "src/lib/v9-regression-bridge.v9.test.ts",
    "src/lib/v9-regression-acceptance-anchors.v9.test.ts",
    "src/lib/v9-coverage-inventory.v9.test.ts",
    "src/lib/v9-api-critical-routes-matrix.v9.test.ts",
    "src/lib/v9-acceptance-criteria.test.ts",
    "src/lib/v9-acceptance-scripts-sync.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "29.2": [
    "src/lib/v9-plan-enforcement-bundles.v9.test.ts",
    "src/lib/v9-appendix-verbatim-anchors.v9.test.ts",
    "src/lib/v9-regression-bridge.v9.test.ts",
    "src/lib/v9-regression-acceptance-anchors.v9.test.ts",
    "src/lib/v9-coverage-inventory.v9.test.ts",
    "src/lib/v9-acceptance-criteria.test.ts",
    "src/lib/v9-acceptance-scripts-sync.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "30": [
    "src/lib/v9-completion-proxies.v9.test.ts",
    "src/lib/v9-measurable-proxies-anchor.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "30.1": [
    "src/lib/v9-completion-proxies.v9.test.ts",
    "src/lib/v9-measurable-proxies-anchor.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "30.2": [
    "src/lib/v9-completion-proxies.v9.test.ts",
    "src/lib/v9-measurable-proxies-anchor.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "30.3": [
    "src/lib/v9-completion-proxies.v9.test.ts",
    "src/lib/v9-measurable-proxies-anchor.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "30.4": [
    "src/lib/v9-completion-proxies.v9.test.ts",
    "src/lib/v9-measurable-proxies-anchor.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "30.5": [
    "src/lib/v9-completion-proxies.v9.test.ts",
    "src/lib/v9-measurable-proxies-anchor.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "30.6": [
    "src/lib/v9-completion-proxies.v9.test.ts",
    "src/lib/v9-measurable-proxies-anchor.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "30.7": [
    "src/lib/v9-completion-proxies.v9.test.ts",
    "src/lib/v9-measurable-proxies-anchor.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "30.8": [
    "src/lib/v9-completion-proxies.v9.test.ts",
    "src/lib/v9-measurable-proxies-anchor.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "30.9": [
    "src/components/layout/v9-page-load-reporter.tsx",
    "src/lib/v9-client-telemetry-strictmode.v9.test.ts",
    "src/lib/v9-completion-proxies.v9.test.ts",
    "src/lib/v9-measurable-proxies-anchor.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "30.10": [
    "src/lib/v9-completion-proxies.v9.test.ts",
    "src/lib/v9-measurable-proxies-anchor.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "31": [
    "src/lib/v9-global-constraints.v9.test.ts",
    "src/lib/v9-plan-enforcement-bundles.v9.test.ts",
    "src/lib/v9-non-goals-guardrails-s31-s32.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
  "32": [
    "src/lib/v9-rollout.ts",
    "src/lib/v9-rollout-inline-queue-kill-switch.v9.test.ts",
    "src/lib/v9-rollout-migrations.v9.test.ts",
    "src/lib/v9-spec-principles.v9.test.ts",
    "src/lib/v9-plan-enforcement-bundles.v9.test.ts",
    "src/lib/v9-non-goals-guardrails-s31-s32.v9.test.ts",
    "src/lib/v9-security-surface-guard.v9.test.ts",
    "src/lib/product-surface/route-inventory.drift.test.ts",
    "src/lib/v9-acceptance-bundle.v9.test.ts",
  ],
} as const;
