/** AUTO-GENERATED — run `npm run generate:debugging-sweep-catalog`. Do not edit by hand. */

export const STUB_CLASS_COUNT = 548 as const;

export const STUB_CLASS_IDS = [
  "ach-nacha-returns",
  "acme-dns-01",
  "acme-tls-alpn-01",
  "active-directory-ldap",
  "adp-workforce-now",
  "ads-b-ais-receiver-only",
  "agora-sdk",
  "airgap-oci-mirror",
  "alertmanager",
  "alloy-analyzer-counterexample",
  "amd-sev-snp",
  "amd-uprof",
  "amplitude-http",
  "android-credential-manager",
  "android-webview",
  "apache-drill",
  "apigee-x",
  "apparmor-profile",
  "appdynamics-machine-agent",
  "archer-grc",
  "arm-trustzone",
  "asyncapi-parser",
  "attribution-reporting-api",
  "audio-asr-failure",
  "automerge-repo",
  "autosar-classic-platform",
  "avalara-ava-tax",
  "avro-schema-resolution",
  "aws-api-gateway-http",
  "aws-iam-policy-simulator",
  "aws-lambda",
  "aws-nitro-enclaves",
  "aws-secrets-manager",
  "aws-shield-advanced",
  "axiom-ingest",
  "azure-dcv2",
  "azure-functions",
  "azure-rbac-abac",
  "bazel-hermetic-sdk",
  "bazel-remote-exec",
  "betterstack-uptime",
  "bimi-vmc",
  "blackbox-exporter",
  "boomi",
  "brazil-lgpd",
  "breakpad-minidump",
  "browserstack-automate",
  "btrfs-enospc",
  "buck2-action-graph",
  "buildkit-cache-mount",
  "buildkite-agent",
  "bun-install-lockfile-drift",
  "bun-runtime",
  "burp-suite-proxy",
  "c2pa-manifest",
  "california-cpra",
  "can-bus-iso15765",
  "canada-pipeda",
  "capacitor-plugin",
  "cargo-crates-io",
  "cargo-deny",
  "cef-arcSight",
  "cert-manager-acme",
  "certificate-transparency-subscriber",
  "cgroups-v2-oom",
  "chain-bom",
  "charles-proxy",
  "chips-settlement",
  "chromatic-ci",
  "chrome-devtools-protocol",
  "chronosphere",
  "chrony-vs-ntpd",
  "circleci-runner",
  "cirq-google-engine",
  "citus-distributed-pg",
  "clang-address-sanitizer",
  "clang-thread-sanitizer",
  "clang-undefined-behavior-sanitizer",
  "cloudflare-waf-only",
  "cloudflare-workers",
  "cloudfront-signed-cookie",
  "cloudfront-signed-url",
  "cluster-primary-death",
  "cobol-batch-bridge",
  "cockroachdb",
  "cocoapods-trunk",
  "color-font-svg-in-ot",
  "connect-buf-build",
  "coq-compilation-stub",
  "coralogix-shipper",
  "coreml-model",
  "cortex-distributor",
  "cosign-sign-blob",
  "cosign-sign-verify",
  "cosign-verify-attestation",
  "cpan-meta",
  "crl-distribution-point-timeout",
  "crlf-gitattributes",
  "cron-vs-anacron",
  "cross-border-tia",
  "crowdin-sync",
  "crowdstrike-falcon-log",
  "csv-sniffer-wrong-delimiter",
  "ctap2-ble",
  "ctap2-nfc",
  "ctap2-usb",
  "cuda-driver",
  "cyclonedx-1-5-json",
  "cypress-io",
  "dane-smime",
  "deno-cache-dir",
  "deno-deploy",
  "deterministic-rng-seed",
  "devicecheck-app-attest",
  "did-key",
  "did-web",
  "diffoscope-html",
  "disa-stig-hardening",
  "discord-webhook",
  "dkim-dmarc-spf-alignment",
  "dns-over-https",
  "dnssec-chain",
  "do-178c-software-level",
  "doppler-sync",
  "dotnet-gc-loh",
  "dpop-bound-tokens",
  "dr-memory",
  "drata",
  "druid",
  "dsym-dwarf-missing",
  "duckdb-embedded",
  "dynatrace-oneagent",
  "ebpf-parca-agent",
  "electric-sql-shape",
  "electron-main-process",
  "endorlabs-sca",
  "eu-ai-act-risk-class",
  "eu-digital-markets-act-hint",
  "evm-json-rpc",
  "executorch-mobile",
  "ext4-journal-abort",
  "f5-bigip",
  "fairplay-streaming",
  "fast-check-shrink-loop",
  "fastly-compute-edge",
  "fastq-parse-gzip",
  "fda-21cfr11-part11",
  "feast-online-store",
  "fedcm-fedcm",
  "fedramp-low-baseline-stub",
  "fedramp-moderate-baseline-stub",
  "fedwire-funds",
  "fiddler-classic",
  "firebolt",
  "firefox-marionette",
  "flagsmith-api",
  "fluent-bit",
  "fossa-cli",
  "foundationdb-record-layer",
  "foundationdb-simulator-class",
  "gamepad-api-mapping",
  "gatekeeper-xattr-quarantine",
  "gcp-cloud-functions",
  "gcp-confidential-vm",
  "gcp-iam-conditions",
  "gcp-secret-manager",
  "gdb-remote-protocol",
  "gdpr-uk-adequacy",
  "geojson-invalid-ring",
  "github-actions-runner-vm",
  "github-oidc-issuer",
  "gitlab-runner",
  "go-proxy-sumdb",
  "go-scheduler-trace",
  "google-chat-webhook",
  "gradle-configuration-cache",
  "gradle-dependency-verification",
  "gradle-plugin-portal",
  "graphite-carbon",
  "graylog-sidecar",
  "growthbook-sdk",
  "grpc-server-reflection",
  "gxp-csv-validation",
  "happy-eyeballs-v2",
  "harfbuzz-buffer-overflow-class",
  "hashicorp-vault-kv2",
  "hex-pm",
  "hipaa-baa-controls-stub",
  "honeycomb-refinery",
  "hsm-aws-cloudhsm",
  "hsm-thales-luna",
  "http-ntlm-negotiate",
  "hypothesis-flaky-example",
  "ibm-db2",
  "ibm-mq",
  "ice-stun-turn",
  "icmp-probe",
  "iec-62443-zone-model",
  "ieee-1588-ptp-boundary-clock",
  "in-toto-run",
  "incident-io-timeline",
  "india-dpdp",
  "influxdb-enterprise",
  "informatica",
  "ini-windows-codepage",
  "instana-host-agent",
  "instrumented-fetch-partial-types",
  "intel-sgx",
  "intel-vtune-hotspots",
  "intercom-conversation",
  "ios-password-autofill",
  "ipv6-ice-literal",
  "iscsi-mpio-path-down",
  "iso-iec-42001",
  "iso27001-annex-a-stub",
  "iso8583-de110-issuer",
  "itar-ear-dual-use-stub",
  "jailbreak-classifier",
  "janus-gateway",
  "jaws-log",
  "jenkins-controller",
  "jepsen-linearizability-class",
  "jira-align",
  "journald",
  "json-schema-draft-2019-09",
  "jvm-g1-pause",
  "jwt-at+jwt",
  "kerberos-kinit",
  "kerberos-spnego",
  "kms-envelope-audit-stub",
  "kong-gateway",
  "kyverno-policy",
  "lacework",
  "lambda-edge",
  "launchd-throttle-interval",
  "launchdarkly-sdk",
  "leef-ibm",
  "leveldb-compaction",
  "libass-subtitle",
  "libfaketime-offset",
  "license-eye",
  "lightstep-satellite",
  "linux-perf-record",
  "livekit",
  "lldb-vscode-adapter",
  "lmdb-mdb-map-full",
  "logstash-beats",
  "logzio-shipper",
  "lokalise-webhook",
  "loki-canary",
  "loki-label-cardinality",
  "loro-crdt",
  "lsf-scheduler",
  "macos-notarization-stapling",
  "mainframe-zos",
  "maven-central",
  "maven-enforcer-plugin",
  "maven-reactor-order",
  "mdns-ice",
  "measured-boot-tpm",
  "metar-taf-parser",
  "mezmo-logdna",
  "microsoft-sqlserver",
  "mimir-distributor",
  "mitmproxy-flow",
  "mixpanel-import",
  "mlflow-tracking-uri",
  "model-card-missing",
  "motherduck",
  "mpi-cluster",
  "ms-teams-adaptive-card",
  "mta-sts-policy",
  "mtls-obtain-cert-acme",
  "mtls-service-mesh-istio",
  "mtls-service-mesh-linkerd",
  "mulesoft",
  "naif-spice-kernel",
  "neon-serverless",
  "neptune-api-token",
  "nerc-cip-bulk-electric",
  "netsuite-suiteql",
  "newrelic-infrastructure",
  "nfs3-stale-file-handle",
  "nist-ai-rmf",
  "nist-csf-subcategory-stub",
  "nitro-enclave",
  "nix-flake-input-lock",
  "nix-store-path-drift",
  "node-stream-backpressure",
  "node-v8-oom",
  "npm-ci-cache-clear",
  "npm-cli-provenance",
  "npm-provenance-attestation",
  "ntp-stratum-monitor",
  "nuclei-template",
  "nuget-feed",
  "nvda-log",
  "nx-graph-cache",
  "nx-run-many-affected",
  "oauth-device-flow",
  "oauth-jar",
  "oauth-par",
  "oci-image-layer-squash",
  "ocsp-stapling",
  "oecd-ai-principles",
  "ofac-screening-batch-stub",
  "offline-sbom-gpg-verify",
  "oid4vci",
  "oid4vp",
  "oidc-fapi",
  "oneapi-level-zero",
  "onnx-runtime",
  "opa-gatekeeper",
  "opc-ua-client-session",
  "openapi-3-1-discriminator",
  "opensearch-data-prepper",
  "opsgenie-alert",
  "oracle-db",
  "orc-stripe-index",
  "otel-semconv-http",
  "owasp-zap-dast",
  "pact-broker-verify",
  "pagerduty-events-v2",
  "palo-alto-fw",
  "pantsbuild-go",
  "papertrail-remote-syslog",
  "parquet-column-pruning",
  "passkey-conditional-ui",
  "passkey-sync-google-password-manager",
  "passkey-sync-icloud-keychain",
  "payment-request-api",
  "pci-saq-aep-stub",
  "pega-platform",
  "percy-snapshot",
  "php-opcache-stale",
  "phrase-tms-api",
  "pinot",
  "pip-audit",
  "planetscale-mysql",
  "play-integrity-standard",
  "playready-client",
  "playwright-cdp-session",
  "playwright-video-retention-policy",
  "pm2-cluster-ipc",
  "pnpm-audit-ci",
  "pnpm-store-corruption",
  "polars-lazy",
  "polarsignals-cloud",
  "postgres-logical-slot-lag",
  "postgrest-embedding-limit",
  "posthog-capture",
  "pouchdb-sync",
  "powersync-bucket",
  "pqc-hybrid-tls",
  "presto-trino",
  "private-aggregation-api",
  "prometheus-pushgateway",
  "prometheus-red-metrics",
  "prometheus-remote-write",
  "prompt-injection-taxonomy",
  "proptest-regressions",
  "pypi-proxy",
  "pyroscope-push",
  "python-gil-asyncio",
  "qiskit-runtime-job",
  "quantum-safe-vpn-stub",
  "questdb",
  "quic-0rtt-replay",
  "ray-data",
  "re2-no-backref",
  "react-native-hermes",
  "rekor-cli-upload",
  "rekor-transparency",
  "risc-v-tee-stub",
  "rmf-control-assessment",
  "rocksdb-write-stall",
  "rocm-driver",
  "rootly-retrospective",
  "rspack-swc",
  "rtp-fednow-instant",
  "ruby-yjit-invalidate",
  "rubygems",
  "rudderstack-transform",
  "rust-tokio-starvation",
  "rxdb-replication",
  "safari-web-inspector",
  "safety-py",
  "safetynet-legacy",
  "saml-xmlsec",
  "sap-rfc",
  "sap-s4hana-odata-v4",
  "sauce-labs",
  "scada-modbus-tcp",
  "scalyr-agent",
  "schrems-ii-scc",
  "screenshot-diff-engine",
  "sctp-data-channel",
  "seccomp-bpf-default",
  "secure-boot-dbx-revocation",
  "secure-enclave-ios",
  "secure-payment-confirmation",
  "selenium-grid-4",
  "selinux-denial-avc",
  "sepa-sct-inst",
  "servicenow-cmdb",
  "shared-storage-api",
  "signalfx-smart-agent",
  "signed-http-exchange",
  "simdjson-parse-error",
  "singlestore",
  "slack-incoming-webhook",
  "slo-error-budget-burn",
  "slsa-build-verifier",
  "slsa-github-generator",
  "slsa-verifier-go",
  "slurm-scheduler",
  "smartcard-piv",
  "smb2-signing-required",
  "snyk-cli",
  "soc2-tsc-mapping-stub",
  "socket-dev-security",
  "solana-rpc",
  "spark-connect",
  "spdx-2-3-tag-value",
  "spiffe-spire",
  "split-io-sdk",
  "splunk-phantom-soar",
  "sqlite-wal-busy",
  "sqlite-wasm",
  "srtp-dtls-handshake",
  "stablecoin-onchain-bridge",
  "starlink-latency-class",
  "statsd",
  "statsig-check-gate",
  "statuspage-api",
  "streaming-json-parse-recovery",
  "stripe-tax-calculation",
  "stryker-mutation-score",
  "stub-sweep-self-telemetry",
  "successfactors-odata-v2",
  "sumologic-collector",
  "supabase-auth-hook-edge",
  "supabase-realtime-channel",
  "supabase-storage-presign-skew",
  "swid-tag",
  "swift-mt103-class",
  "synthetic-blackbox-class",
  "synthetic-ct-log-class",
  "synthetic-icmp-class",
  "synthetic-ntp-class",
  "syslog-rfc5424",
  "systemd-restart-on-failure",
  "systemd-unit-restart-storm",
  "tail-sampling-probabilistic",
  "talkback-ci",
  "tauri-runtime",
  "taxjar-api",
  "tcp-fast-open",
  "tcpdump-pcap",
  "tecton-materialization",
  "tensorboard-grpc",
  "tensorrt-engine",
  "thanos-receive",
  "tibco-emsl",
  "tidb-distributed",
  "timescale-promscale",
  "timescaledb",
  "tlc-model-checker-oom",
  "tlc-state-explosion",
  "tls-ech-client",
  "tls-rpt-aggregate",
  "tls-session-tickets-rotation",
  "tolgee-cli",
  "toml-datetime-offset",
  "topics-api-deprecated",
  "tpm-2.0-attestation-stub",
  "transform-objectmode",
  "triton-inference-server",
  "trpc-batch-link",
  "turbo-daemon-socket",
  "turbopack-incremental",
  "turborepo-remote-cache",
  "twirp-hpk-wire",
  "tyk-gateway",
  "uefi-secure-boot",
  "unity-webgl-runtime",
  "unleash-server",
  "unreal-pixel-streaming",
  "valgrind-memcheck",
  "vanta",
  "variable-font-wght-wdth-slnt",
  "vcf-multiallelic",
  "vector-dev",
  "vercel-edge",
  "vercel-edge-config",
  "vercel-fluid",
  "vercel-kv",
  "vibrate-api-sandwich",
  "victoriametrics-single",
  "vision-model-ocr-failure",
  "vite-optimize-deps",
  "vllm-openai-api",
  "voiceover-ci",
  "volatility-plugin-stub",
  "w3c-vc-jwt",
  "w3c-vc-ld",
  "wal2json-decoder",
  "wamr-iwasm",
  "wandb-run-crash",
  "wasm-component-model",
  "wasmer-runtime",
  "wasmtime-runtime",
  "wavefront-proxy",
  "web-bundle-wbn",
  "web-serial-port",
  "webbluetooth-gatt",
  "webdriverio-runner",
  "webgpu-compute-shader",
  "webhid-claim",
  "webid-direct",
  "webmethods",
  "webnfc-ndef",
  "webnn-graph",
  "webpack-cache-pack",
  "webrtc-sfu",
  "webusb-device-filter",
  "webvtt-parser",
  "widevine-l1-hdcp",
  "widevine-l3-sw",
  "win32-long-path",
  "windows-event-log-forwarding",
  "witness-bom",
  "workday-raas",
  "worker-thread-uncaught",
  "ws-fed",
  "wsl2-glibc-mismatch",
  "xcode-instruments-time-profiler",
  "xfs-repair-force",
  "yaml-merge-key-unsafe",
  "yarn-berry-integrity",
  "yarn-berry-zipfs",
  "yjs-doc",
  "yubikey-fido",
  "yugabyte-ysql",
  "zendesk-sunshine-conversations",
  "zendesk-ticket-api",
  "zfs-scrub-io",
  "zscaler-zpa"
] as const;

export const STUB_CLASS_REGISTRY: Record<string, () => void> = {
  "ach-nacha-returns": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ach-nacha-returns"); },
  "acme-dns-01": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "acme-dns-01"); },
  "acme-tls-alpn-01": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "acme-tls-alpn-01"); },
  "active-directory-ldap": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "active-directory-ldap"); },
  "adp-workforce-now": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "adp-workforce-now"); },
  "ads-b-ais-receiver-only": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ads-b-ais-receiver-only"); },
  "agora-sdk": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "agora-sdk"); },
  "airgap-oci-mirror": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "airgap-oci-mirror"); },
  "alertmanager": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "alertmanager"); },
  "alloy-analyzer-counterexample": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "alloy-analyzer-counterexample"); },
  "amd-sev-snp": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "amd-sev-snp"); },
  "amd-uprof": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "amd-uprof"); },
  "amplitude-http": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "amplitude-http"); },
  "android-credential-manager": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "android-credential-manager"); },
  "android-webview": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "android-webview"); },
  "apache-drill": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "apache-drill"); },
  "apigee-x": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "apigee-x"); },
  "apparmor-profile": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "apparmor-profile"); },
  "appdynamics-machine-agent": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "appdynamics-machine-agent"); },
  "archer-grc": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "archer-grc"); },
  "arm-trustzone": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "arm-trustzone"); },
  "asyncapi-parser": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "asyncapi-parser"); },
  "attribution-reporting-api": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "attribution-reporting-api"); },
  "audio-asr-failure": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "audio-asr-failure"); },
  "automerge-repo": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "automerge-repo"); },
  "autosar-classic-platform": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "autosar-classic-platform"); },
  "avalara-ava-tax": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "avalara-ava-tax"); },
  "avro-schema-resolution": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "avro-schema-resolution"); },
  "aws-api-gateway-http": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "aws-api-gateway-http"); },
  "aws-iam-policy-simulator": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "aws-iam-policy-simulator"); },
  "aws-lambda": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "aws-lambda"); },
  "aws-nitro-enclaves": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "aws-nitro-enclaves"); },
  "aws-secrets-manager": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "aws-secrets-manager"); },
  "aws-shield-advanced": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "aws-shield-advanced"); },
  "axiom-ingest": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "axiom-ingest"); },
  "azure-dcv2": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "azure-dcv2"); },
  "azure-functions": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "azure-functions"); },
  "azure-rbac-abac": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "azure-rbac-abac"); },
  "bazel-hermetic-sdk": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "bazel-hermetic-sdk"); },
  "bazel-remote-exec": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "bazel-remote-exec"); },
  "betterstack-uptime": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "betterstack-uptime"); },
  "bimi-vmc": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "bimi-vmc"); },
  "blackbox-exporter": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "blackbox-exporter"); },
  "boomi": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "boomi"); },
  "brazil-lgpd": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "brazil-lgpd"); },
  "breakpad-minidump": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "breakpad-minidump"); },
  "browserstack-automate": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "browserstack-automate"); },
  "btrfs-enospc": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "btrfs-enospc"); },
  "buck2-action-graph": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "buck2-action-graph"); },
  "buildkit-cache-mount": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "buildkit-cache-mount"); },
  "buildkite-agent": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "buildkite-agent"); },
  "bun-install-lockfile-drift": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "bun-install-lockfile-drift"); },
  "bun-runtime": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "bun-runtime"); },
  "burp-suite-proxy": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "burp-suite-proxy"); },
  "c2pa-manifest": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "c2pa-manifest"); },
  "california-cpra": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "california-cpra"); },
  "can-bus-iso15765": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "can-bus-iso15765"); },
  "canada-pipeda": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "canada-pipeda"); },
  "capacitor-plugin": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "capacitor-plugin"); },
  "cargo-crates-io": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cargo-crates-io"); },
  "cargo-deny": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cargo-deny"); },
  "cef-arcSight": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cef-arcSight"); },
  "cert-manager-acme": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cert-manager-acme"); },
  "certificate-transparency-subscriber": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "certificate-transparency-subscriber"); },
  "cgroups-v2-oom": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cgroups-v2-oom"); },
  "chain-bom": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "chain-bom"); },
  "charles-proxy": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "charles-proxy"); },
  "chips-settlement": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "chips-settlement"); },
  "chromatic-ci": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "chromatic-ci"); },
  "chrome-devtools-protocol": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "chrome-devtools-protocol"); },
  "chronosphere": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "chronosphere"); },
  "chrony-vs-ntpd": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "chrony-vs-ntpd"); },
  "circleci-runner": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "circleci-runner"); },
  "cirq-google-engine": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cirq-google-engine"); },
  "citus-distributed-pg": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "citus-distributed-pg"); },
  "clang-address-sanitizer": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "clang-address-sanitizer"); },
  "clang-thread-sanitizer": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "clang-thread-sanitizer"); },
  "clang-undefined-behavior-sanitizer": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "clang-undefined-behavior-sanitizer"); },
  "cloudflare-waf-only": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cloudflare-waf-only"); },
  "cloudflare-workers": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cloudflare-workers"); },
  "cloudfront-signed-cookie": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cloudfront-signed-cookie"); },
  "cloudfront-signed-url": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cloudfront-signed-url"); },
  "cluster-primary-death": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cluster-primary-death"); },
  "cobol-batch-bridge": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cobol-batch-bridge"); },
  "cockroachdb": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cockroachdb"); },
  "cocoapods-trunk": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cocoapods-trunk"); },
  "color-font-svg-in-ot": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "color-font-svg-in-ot"); },
  "connect-buf-build": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "connect-buf-build"); },
  "coq-compilation-stub": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "coq-compilation-stub"); },
  "coralogix-shipper": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "coralogix-shipper"); },
  "coreml-model": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "coreml-model"); },
  "cortex-distributor": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cortex-distributor"); },
  "cosign-sign-blob": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cosign-sign-blob"); },
  "cosign-sign-verify": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cosign-sign-verify"); },
  "cosign-verify-attestation": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cosign-verify-attestation"); },
  "cpan-meta": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cpan-meta"); },
  "crl-distribution-point-timeout": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "crl-distribution-point-timeout"); },
  "crlf-gitattributes": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "crlf-gitattributes"); },
  "cron-vs-anacron": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cron-vs-anacron"); },
  "cross-border-tia": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cross-border-tia"); },
  "crowdin-sync": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "crowdin-sync"); },
  "crowdstrike-falcon-log": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "crowdstrike-falcon-log"); },
  "csv-sniffer-wrong-delimiter": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "csv-sniffer-wrong-delimiter"); },
  "ctap2-ble": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ctap2-ble"); },
  "ctap2-nfc": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ctap2-nfc"); },
  "ctap2-usb": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ctap2-usb"); },
  "cuda-driver": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cuda-driver"); },
  "cyclonedx-1-5-json": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cyclonedx-1-5-json"); },
  "cypress-io": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "cypress-io"); },
  "dane-smime": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "dane-smime"); },
  "deno-cache-dir": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "deno-cache-dir"); },
  "deno-deploy": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "deno-deploy"); },
  "deterministic-rng-seed": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "deterministic-rng-seed"); },
  "devicecheck-app-attest": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "devicecheck-app-attest"); },
  "did-key": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "did-key"); },
  "did-web": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "did-web"); },
  "diffoscope-html": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "diffoscope-html"); },
  "disa-stig-hardening": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "disa-stig-hardening"); },
  "discord-webhook": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "discord-webhook"); },
  "dkim-dmarc-spf-alignment": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "dkim-dmarc-spf-alignment"); },
  "dns-over-https": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "dns-over-https"); },
  "dnssec-chain": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "dnssec-chain"); },
  "do-178c-software-level": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "do-178c-software-level"); },
  "doppler-sync": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "doppler-sync"); },
  "dotnet-gc-loh": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "dotnet-gc-loh"); },
  "dpop-bound-tokens": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "dpop-bound-tokens"); },
  "dr-memory": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "dr-memory"); },
  "drata": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "drata"); },
  "druid": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "druid"); },
  "dsym-dwarf-missing": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "dsym-dwarf-missing"); },
  "duckdb-embedded": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "duckdb-embedded"); },
  "dynatrace-oneagent": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "dynatrace-oneagent"); },
  "ebpf-parca-agent": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ebpf-parca-agent"); },
  "electric-sql-shape": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "electric-sql-shape"); },
  "electron-main-process": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "electron-main-process"); },
  "endorlabs-sca": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "endorlabs-sca"); },
  "eu-ai-act-risk-class": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "eu-ai-act-risk-class"); },
  "eu-digital-markets-act-hint": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "eu-digital-markets-act-hint"); },
  "evm-json-rpc": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "evm-json-rpc"); },
  "executorch-mobile": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "executorch-mobile"); },
  "ext4-journal-abort": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ext4-journal-abort"); },
  "f5-bigip": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "f5-bigip"); },
  "fairplay-streaming": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "fairplay-streaming"); },
  "fast-check-shrink-loop": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "fast-check-shrink-loop"); },
  "fastly-compute-edge": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "fastly-compute-edge"); },
  "fastq-parse-gzip": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "fastq-parse-gzip"); },
  "fda-21cfr11-part11": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "fda-21cfr11-part11"); },
  "feast-online-store": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "feast-online-store"); },
  "fedcm-fedcm": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "fedcm-fedcm"); },
  "fedramp-low-baseline-stub": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "fedramp-low-baseline-stub"); },
  "fedramp-moderate-baseline-stub": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "fedramp-moderate-baseline-stub"); },
  "fedwire-funds": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "fedwire-funds"); },
  "fiddler-classic": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "fiddler-classic"); },
  "firebolt": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "firebolt"); },
  "firefox-marionette": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "firefox-marionette"); },
  "flagsmith-api": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "flagsmith-api"); },
  "fluent-bit": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "fluent-bit"); },
  "fossa-cli": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "fossa-cli"); },
  "foundationdb-record-layer": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "foundationdb-record-layer"); },
  "foundationdb-simulator-class": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "foundationdb-simulator-class"); },
  "gamepad-api-mapping": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "gamepad-api-mapping"); },
  "gatekeeper-xattr-quarantine": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "gatekeeper-xattr-quarantine"); },
  "gcp-cloud-functions": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "gcp-cloud-functions"); },
  "gcp-confidential-vm": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "gcp-confidential-vm"); },
  "gcp-iam-conditions": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "gcp-iam-conditions"); },
  "gcp-secret-manager": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "gcp-secret-manager"); },
  "gdb-remote-protocol": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "gdb-remote-protocol"); },
  "gdpr-uk-adequacy": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "gdpr-uk-adequacy"); },
  "geojson-invalid-ring": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "geojson-invalid-ring"); },
  "github-actions-runner-vm": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "github-actions-runner-vm"); },
  "github-oidc-issuer": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "github-oidc-issuer"); },
  "gitlab-runner": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "gitlab-runner"); },
  "go-proxy-sumdb": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "go-proxy-sumdb"); },
  "go-scheduler-trace": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "go-scheduler-trace"); },
  "google-chat-webhook": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "google-chat-webhook"); },
  "gradle-configuration-cache": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "gradle-configuration-cache"); },
  "gradle-dependency-verification": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "gradle-dependency-verification"); },
  "gradle-plugin-portal": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "gradle-plugin-portal"); },
  "graphite-carbon": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "graphite-carbon"); },
  "graylog-sidecar": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "graylog-sidecar"); },
  "growthbook-sdk": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "growthbook-sdk"); },
  "grpc-server-reflection": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "grpc-server-reflection"); },
  "gxp-csv-validation": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "gxp-csv-validation"); },
  "happy-eyeballs-v2": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "happy-eyeballs-v2"); },
  "harfbuzz-buffer-overflow-class": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "harfbuzz-buffer-overflow-class"); },
  "hashicorp-vault-kv2": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "hashicorp-vault-kv2"); },
  "hex-pm": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "hex-pm"); },
  "hipaa-baa-controls-stub": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "hipaa-baa-controls-stub"); },
  "honeycomb-refinery": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "honeycomb-refinery"); },
  "hsm-aws-cloudhsm": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "hsm-aws-cloudhsm"); },
  "hsm-thales-luna": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "hsm-thales-luna"); },
  "http-ntlm-negotiate": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "http-ntlm-negotiate"); },
  "hypothesis-flaky-example": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "hypothesis-flaky-example"); },
  "ibm-db2": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ibm-db2"); },
  "ibm-mq": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ibm-mq"); },
  "ice-stun-turn": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ice-stun-turn"); },
  "icmp-probe": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "icmp-probe"); },
  "iec-62443-zone-model": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "iec-62443-zone-model"); },
  "ieee-1588-ptp-boundary-clock": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ieee-1588-ptp-boundary-clock"); },
  "in-toto-run": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "in-toto-run"); },
  "incident-io-timeline": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "incident-io-timeline"); },
  "india-dpdp": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "india-dpdp"); },
  "influxdb-enterprise": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "influxdb-enterprise"); },
  "informatica": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "informatica"); },
  "ini-windows-codepage": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ini-windows-codepage"); },
  "instana-host-agent": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "instana-host-agent"); },
  "instrumented-fetch-partial-types": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "instrumented-fetch-partial-types"); },
  "intel-sgx": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "intel-sgx"); },
  "intel-vtune-hotspots": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "intel-vtune-hotspots"); },
  "intercom-conversation": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "intercom-conversation"); },
  "ios-password-autofill": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ios-password-autofill"); },
  "ipv6-ice-literal": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ipv6-ice-literal"); },
  "iscsi-mpio-path-down": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "iscsi-mpio-path-down"); },
  "iso-iec-42001": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "iso-iec-42001"); },
  "iso27001-annex-a-stub": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "iso27001-annex-a-stub"); },
  "iso8583-de110-issuer": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "iso8583-de110-issuer"); },
  "itar-ear-dual-use-stub": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "itar-ear-dual-use-stub"); },
  "jailbreak-classifier": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "jailbreak-classifier"); },
  "janus-gateway": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "janus-gateway"); },
  "jaws-log": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "jaws-log"); },
  "jenkins-controller": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "jenkins-controller"); },
  "jepsen-linearizability-class": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "jepsen-linearizability-class"); },
  "jira-align": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "jira-align"); },
  "journald": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "journald"); },
  "json-schema-draft-2019-09": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "json-schema-draft-2019-09"); },
  "jvm-g1-pause": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "jvm-g1-pause"); },
  "jwt-at+jwt": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "jwt-at+jwt"); },
  "kerberos-kinit": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "kerberos-kinit"); },
  "kerberos-spnego": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "kerberos-spnego"); },
  "kms-envelope-audit-stub": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "kms-envelope-audit-stub"); },
  "kong-gateway": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "kong-gateway"); },
  "kyverno-policy": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "kyverno-policy"); },
  "lacework": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "lacework"); },
  "lambda-edge": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "lambda-edge"); },
  "launchd-throttle-interval": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "launchd-throttle-interval"); },
  "launchdarkly-sdk": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "launchdarkly-sdk"); },
  "leef-ibm": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "leef-ibm"); },
  "leveldb-compaction": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "leveldb-compaction"); },
  "libass-subtitle": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "libass-subtitle"); },
  "libfaketime-offset": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "libfaketime-offset"); },
  "license-eye": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "license-eye"); },
  "lightstep-satellite": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "lightstep-satellite"); },
  "linux-perf-record": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "linux-perf-record"); },
  "livekit": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "livekit"); },
  "lldb-vscode-adapter": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "lldb-vscode-adapter"); },
  "lmdb-mdb-map-full": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "lmdb-mdb-map-full"); },
  "logstash-beats": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "logstash-beats"); },
  "logzio-shipper": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "logzio-shipper"); },
  "lokalise-webhook": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "lokalise-webhook"); },
  "loki-canary": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "loki-canary"); },
  "loki-label-cardinality": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "loki-label-cardinality"); },
  "loro-crdt": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "loro-crdt"); },
  "lsf-scheduler": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "lsf-scheduler"); },
  "macos-notarization-stapling": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "macos-notarization-stapling"); },
  "mainframe-zos": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "mainframe-zos"); },
  "maven-central": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "maven-central"); },
  "maven-enforcer-plugin": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "maven-enforcer-plugin"); },
  "maven-reactor-order": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "maven-reactor-order"); },
  "mdns-ice": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "mdns-ice"); },
  "measured-boot-tpm": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "measured-boot-tpm"); },
  "metar-taf-parser": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "metar-taf-parser"); },
  "mezmo-logdna": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "mezmo-logdna"); },
  "microsoft-sqlserver": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "microsoft-sqlserver"); },
  "mimir-distributor": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "mimir-distributor"); },
  "mitmproxy-flow": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "mitmproxy-flow"); },
  "mixpanel-import": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "mixpanel-import"); },
  "mlflow-tracking-uri": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "mlflow-tracking-uri"); },
  "model-card-missing": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "model-card-missing"); },
  "motherduck": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "motherduck"); },
  "mpi-cluster": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "mpi-cluster"); },
  "ms-teams-adaptive-card": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ms-teams-adaptive-card"); },
  "mta-sts-policy": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "mta-sts-policy"); },
  "mtls-obtain-cert-acme": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "mtls-obtain-cert-acme"); },
  "mtls-service-mesh-istio": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "mtls-service-mesh-istio"); },
  "mtls-service-mesh-linkerd": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "mtls-service-mesh-linkerd"); },
  "mulesoft": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "mulesoft"); },
  "naif-spice-kernel": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "naif-spice-kernel"); },
  "neon-serverless": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "neon-serverless"); },
  "neptune-api-token": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "neptune-api-token"); },
  "nerc-cip-bulk-electric": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "nerc-cip-bulk-electric"); },
  "netsuite-suiteql": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "netsuite-suiteql"); },
  "newrelic-infrastructure": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "newrelic-infrastructure"); },
  "nfs3-stale-file-handle": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "nfs3-stale-file-handle"); },
  "nist-ai-rmf": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "nist-ai-rmf"); },
  "nist-csf-subcategory-stub": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "nist-csf-subcategory-stub"); },
  "nitro-enclave": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "nitro-enclave"); },
  "nix-flake-input-lock": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "nix-flake-input-lock"); },
  "nix-store-path-drift": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "nix-store-path-drift"); },
  "node-stream-backpressure": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "node-stream-backpressure"); },
  "node-v8-oom": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "node-v8-oom"); },
  "npm-ci-cache-clear": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "npm-ci-cache-clear"); },
  "npm-cli-provenance": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "npm-cli-provenance"); },
  "npm-provenance-attestation": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "npm-provenance-attestation"); },
  "ntp-stratum-monitor": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ntp-stratum-monitor"); },
  "nuclei-template": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "nuclei-template"); },
  "nuget-feed": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "nuget-feed"); },
  "nvda-log": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "nvda-log"); },
  "nx-graph-cache": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "nx-graph-cache"); },
  "nx-run-many-affected": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "nx-run-many-affected"); },
  "oauth-device-flow": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "oauth-device-flow"); },
  "oauth-jar": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "oauth-jar"); },
  "oauth-par": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "oauth-par"); },
  "oci-image-layer-squash": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "oci-image-layer-squash"); },
  "ocsp-stapling": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ocsp-stapling"); },
  "oecd-ai-principles": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "oecd-ai-principles"); },
  "ofac-screening-batch-stub": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ofac-screening-batch-stub"); },
  "offline-sbom-gpg-verify": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "offline-sbom-gpg-verify"); },
  "oid4vci": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "oid4vci"); },
  "oid4vp": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "oid4vp"); },
  "oidc-fapi": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "oidc-fapi"); },
  "oneapi-level-zero": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "oneapi-level-zero"); },
  "onnx-runtime": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "onnx-runtime"); },
  "opa-gatekeeper": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "opa-gatekeeper"); },
  "opc-ua-client-session": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "opc-ua-client-session"); },
  "openapi-3-1-discriminator": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "openapi-3-1-discriminator"); },
  "opensearch-data-prepper": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "opensearch-data-prepper"); },
  "opsgenie-alert": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "opsgenie-alert"); },
  "oracle-db": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "oracle-db"); },
  "orc-stripe-index": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "orc-stripe-index"); },
  "otel-semconv-http": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "otel-semconv-http"); },
  "owasp-zap-dast": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "owasp-zap-dast"); },
  "pact-broker-verify": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "pact-broker-verify"); },
  "pagerduty-events-v2": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "pagerduty-events-v2"); },
  "palo-alto-fw": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "palo-alto-fw"); },
  "pantsbuild-go": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "pantsbuild-go"); },
  "papertrail-remote-syslog": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "papertrail-remote-syslog"); },
  "parquet-column-pruning": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "parquet-column-pruning"); },
  "passkey-conditional-ui": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "passkey-conditional-ui"); },
  "passkey-sync-google-password-manager": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "passkey-sync-google-password-manager"); },
  "passkey-sync-icloud-keychain": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "passkey-sync-icloud-keychain"); },
  "payment-request-api": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "payment-request-api"); },
  "pci-saq-aep-stub": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "pci-saq-aep-stub"); },
  "pega-platform": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "pega-platform"); },
  "percy-snapshot": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "percy-snapshot"); },
  "php-opcache-stale": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "php-opcache-stale"); },
  "phrase-tms-api": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "phrase-tms-api"); },
  "pinot": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "pinot"); },
  "pip-audit": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "pip-audit"); },
  "planetscale-mysql": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "planetscale-mysql"); },
  "play-integrity-standard": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "play-integrity-standard"); },
  "playready-client": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "playready-client"); },
  "playwright-cdp-session": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "playwright-cdp-session"); },
  "playwright-video-retention-policy": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "playwright-video-retention-policy"); },
  "pm2-cluster-ipc": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "pm2-cluster-ipc"); },
  "pnpm-audit-ci": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "pnpm-audit-ci"); },
  "pnpm-store-corruption": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "pnpm-store-corruption"); },
  "polars-lazy": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "polars-lazy"); },
  "polarsignals-cloud": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "polarsignals-cloud"); },
  "postgres-logical-slot-lag": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "postgres-logical-slot-lag"); },
  "postgrest-embedding-limit": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "postgrest-embedding-limit"); },
  "posthog-capture": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "posthog-capture"); },
  "pouchdb-sync": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "pouchdb-sync"); },
  "powersync-bucket": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "powersync-bucket"); },
  "pqc-hybrid-tls": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "pqc-hybrid-tls"); },
  "presto-trino": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "presto-trino"); },
  "private-aggregation-api": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "private-aggregation-api"); },
  "prometheus-pushgateway": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "prometheus-pushgateway"); },
  "prometheus-red-metrics": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "prometheus-red-metrics"); },
  "prometheus-remote-write": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "prometheus-remote-write"); },
  "prompt-injection-taxonomy": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "prompt-injection-taxonomy"); },
  "proptest-regressions": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "proptest-regressions"); },
  "pypi-proxy": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "pypi-proxy"); },
  "pyroscope-push": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "pyroscope-push"); },
  "python-gil-asyncio": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "python-gil-asyncio"); },
  "qiskit-runtime-job": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "qiskit-runtime-job"); },
  "quantum-safe-vpn-stub": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "quantum-safe-vpn-stub"); },
  "questdb": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "questdb"); },
  "quic-0rtt-replay": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "quic-0rtt-replay"); },
  "ray-data": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ray-data"); },
  "re2-no-backref": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "re2-no-backref"); },
  "react-native-hermes": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "react-native-hermes"); },
  "rekor-cli-upload": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "rekor-cli-upload"); },
  "rekor-transparency": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "rekor-transparency"); },
  "risc-v-tee-stub": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "risc-v-tee-stub"); },
  "rmf-control-assessment": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "rmf-control-assessment"); },
  "rocksdb-write-stall": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "rocksdb-write-stall"); },
  "rocm-driver": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "rocm-driver"); },
  "rootly-retrospective": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "rootly-retrospective"); },
  "rspack-swc": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "rspack-swc"); },
  "rtp-fednow-instant": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "rtp-fednow-instant"); },
  "ruby-yjit-invalidate": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ruby-yjit-invalidate"); },
  "rubygems": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "rubygems"); },
  "rudderstack-transform": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "rudderstack-transform"); },
  "rust-tokio-starvation": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "rust-tokio-starvation"); },
  "rxdb-replication": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "rxdb-replication"); },
  "safari-web-inspector": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "safari-web-inspector"); },
  "safety-py": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "safety-py"); },
  "safetynet-legacy": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "safetynet-legacy"); },
  "saml-xmlsec": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "saml-xmlsec"); },
  "sap-rfc": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "sap-rfc"); },
  "sap-s4hana-odata-v4": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "sap-s4hana-odata-v4"); },
  "sauce-labs": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "sauce-labs"); },
  "scada-modbus-tcp": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "scada-modbus-tcp"); },
  "scalyr-agent": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "scalyr-agent"); },
  "schrems-ii-scc": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "schrems-ii-scc"); },
  "screenshot-diff-engine": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "screenshot-diff-engine"); },
  "sctp-data-channel": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "sctp-data-channel"); },
  "seccomp-bpf-default": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "seccomp-bpf-default"); },
  "secure-boot-dbx-revocation": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "secure-boot-dbx-revocation"); },
  "secure-enclave-ios": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "secure-enclave-ios"); },
  "secure-payment-confirmation": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "secure-payment-confirmation"); },
  "selenium-grid-4": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "selenium-grid-4"); },
  "selinux-denial-avc": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "selinux-denial-avc"); },
  "sepa-sct-inst": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "sepa-sct-inst"); },
  "servicenow-cmdb": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "servicenow-cmdb"); },
  "shared-storage-api": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "shared-storage-api"); },
  "signalfx-smart-agent": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "signalfx-smart-agent"); },
  "signed-http-exchange": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "signed-http-exchange"); },
  "simdjson-parse-error": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "simdjson-parse-error"); },
  "singlestore": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "singlestore"); },
  "slack-incoming-webhook": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "slack-incoming-webhook"); },
  "slo-error-budget-burn": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "slo-error-budget-burn"); },
  "slsa-build-verifier": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "slsa-build-verifier"); },
  "slsa-github-generator": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "slsa-github-generator"); },
  "slsa-verifier-go": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "slsa-verifier-go"); },
  "slurm-scheduler": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "slurm-scheduler"); },
  "smartcard-piv": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "smartcard-piv"); },
  "smb2-signing-required": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "smb2-signing-required"); },
  "snyk-cli": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "snyk-cli"); },
  "soc2-tsc-mapping-stub": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "soc2-tsc-mapping-stub"); },
  "socket-dev-security": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "socket-dev-security"); },
  "solana-rpc": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "solana-rpc"); },
  "spark-connect": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "spark-connect"); },
  "spdx-2-3-tag-value": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "spdx-2-3-tag-value"); },
  "spiffe-spire": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "spiffe-spire"); },
  "split-io-sdk": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "split-io-sdk"); },
  "splunk-phantom-soar": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "splunk-phantom-soar"); },
  "sqlite-wal-busy": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "sqlite-wal-busy"); },
  "sqlite-wasm": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "sqlite-wasm"); },
  "srtp-dtls-handshake": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "srtp-dtls-handshake"); },
  "stablecoin-onchain-bridge": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "stablecoin-onchain-bridge"); },
  "starlink-latency-class": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "starlink-latency-class"); },
  "statsd": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "statsd"); },
  "statsig-check-gate": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "statsig-check-gate"); },
  "statuspage-api": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "statuspage-api"); },
  "streaming-json-parse-recovery": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "streaming-json-parse-recovery"); },
  "stripe-tax-calculation": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "stripe-tax-calculation"); },
  "stryker-mutation-score": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "stryker-mutation-score"); },
  "stub-sweep-self-telemetry": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "stub-sweep-self-telemetry"); },
  "successfactors-odata-v2": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "successfactors-odata-v2"); },
  "sumologic-collector": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "sumologic-collector"); },
  "supabase-auth-hook-edge": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "supabase-auth-hook-edge"); },
  "supabase-realtime-channel": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "supabase-realtime-channel"); },
  "supabase-storage-presign-skew": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "supabase-storage-presign-skew"); },
  "swid-tag": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "swid-tag"); },
  "swift-mt103-class": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "swift-mt103-class"); },
  "synthetic-blackbox-class": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "synthetic-blackbox-class"); },
  "synthetic-ct-log-class": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "synthetic-ct-log-class"); },
  "synthetic-icmp-class": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "synthetic-icmp-class"); },
  "synthetic-ntp-class": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "synthetic-ntp-class"); },
  "syslog-rfc5424": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "syslog-rfc5424"); },
  "systemd-restart-on-failure": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "systemd-restart-on-failure"); },
  "systemd-unit-restart-storm": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "systemd-unit-restart-storm"); },
  "tail-sampling-probabilistic": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tail-sampling-probabilistic"); },
  "talkback-ci": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "talkback-ci"); },
  "tauri-runtime": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tauri-runtime"); },
  "taxjar-api": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "taxjar-api"); },
  "tcp-fast-open": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tcp-fast-open"); },
  "tcpdump-pcap": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tcpdump-pcap"); },
  "tecton-materialization": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tecton-materialization"); },
  "tensorboard-grpc": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tensorboard-grpc"); },
  "tensorrt-engine": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tensorrt-engine"); },
  "thanos-receive": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "thanos-receive"); },
  "tibco-emsl": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tibco-emsl"); },
  "tidb-distributed": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tidb-distributed"); },
  "timescale-promscale": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "timescale-promscale"); },
  "timescaledb": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "timescaledb"); },
  "tlc-model-checker-oom": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tlc-model-checker-oom"); },
  "tlc-state-explosion": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tlc-state-explosion"); },
  "tls-ech-client": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tls-ech-client"); },
  "tls-rpt-aggregate": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tls-rpt-aggregate"); },
  "tls-session-tickets-rotation": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tls-session-tickets-rotation"); },
  "tolgee-cli": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tolgee-cli"); },
  "toml-datetime-offset": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "toml-datetime-offset"); },
  "topics-api-deprecated": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "topics-api-deprecated"); },
  "tpm-2.0-attestation-stub": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tpm-2.0-attestation-stub"); },
  "transform-objectmode": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "transform-objectmode"); },
  "triton-inference-server": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "triton-inference-server"); },
  "trpc-batch-link": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "trpc-batch-link"); },
  "turbo-daemon-socket": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "turbo-daemon-socket"); },
  "turbopack-incremental": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "turbopack-incremental"); },
  "turborepo-remote-cache": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "turborepo-remote-cache"); },
  "twirp-hpk-wire": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "twirp-hpk-wire"); },
  "tyk-gateway": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "tyk-gateway"); },
  "uefi-secure-boot": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "uefi-secure-boot"); },
  "unity-webgl-runtime": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "unity-webgl-runtime"); },
  "unleash-server": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "unleash-server"); },
  "unreal-pixel-streaming": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "unreal-pixel-streaming"); },
  "valgrind-memcheck": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "valgrind-memcheck"); },
  "vanta": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "vanta"); },
  "variable-font-wght-wdth-slnt": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "variable-font-wght-wdth-slnt"); },
  "vcf-multiallelic": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "vcf-multiallelic"); },
  "vector-dev": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "vector-dev"); },
  "vercel-edge": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "vercel-edge"); },
  "vercel-edge-config": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "vercel-edge-config"); },
  "vercel-fluid": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "vercel-fluid"); },
  "vercel-kv": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "vercel-kv"); },
  "vibrate-api-sandwich": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "vibrate-api-sandwich"); },
  "victoriametrics-single": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "victoriametrics-single"); },
  "vision-model-ocr-failure": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "vision-model-ocr-failure"); },
  "vite-optimize-deps": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "vite-optimize-deps"); },
  "vllm-openai-api": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "vllm-openai-api"); },
  "voiceover-ci": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "voiceover-ci"); },
  "volatility-plugin-stub": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "volatility-plugin-stub"); },
  "w3c-vc-jwt": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "w3c-vc-jwt"); },
  "w3c-vc-ld": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "w3c-vc-ld"); },
  "wal2json-decoder": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "wal2json-decoder"); },
  "wamr-iwasm": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "wamr-iwasm"); },
  "wandb-run-crash": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "wandb-run-crash"); },
  "wasm-component-model": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "wasm-component-model"); },
  "wasmer-runtime": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "wasmer-runtime"); },
  "wasmtime-runtime": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "wasmtime-runtime"); },
  "wavefront-proxy": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "wavefront-proxy"); },
  "web-bundle-wbn": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "web-bundle-wbn"); },
  "web-serial-port": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "web-serial-port"); },
  "webbluetooth-gatt": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "webbluetooth-gatt"); },
  "webdriverio-runner": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "webdriverio-runner"); },
  "webgpu-compute-shader": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "webgpu-compute-shader"); },
  "webhid-claim": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "webhid-claim"); },
  "webid-direct": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "webid-direct"); },
  "webmethods": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "webmethods"); },
  "webnfc-ndef": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "webnfc-ndef"); },
  "webnn-graph": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "webnn-graph"); },
  "webpack-cache-pack": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "webpack-cache-pack"); },
  "webrtc-sfu": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "webrtc-sfu"); },
  "webusb-device-filter": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "webusb-device-filter"); },
  "webvtt-parser": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "webvtt-parser"); },
  "widevine-l1-hdcp": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "widevine-l1-hdcp"); },
  "widevine-l3-sw": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "widevine-l3-sw"); },
  "win32-long-path": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "win32-long-path"); },
  "windows-event-log-forwarding": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "windows-event-log-forwarding"); },
  "witness-bom": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "witness-bom"); },
  "workday-raas": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "workday-raas"); },
  "worker-thread-uncaught": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "worker-thread-uncaught"); },
  "ws-fed": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "ws-fed"); },
  "wsl2-glibc-mismatch": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "wsl2-glibc-mismatch"); },
  "xcode-instruments-time-profiler": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "xcode-instruments-time-profiler"); },
  "xfs-repair-force": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "xfs-repair-force"); },
  "yaml-merge-key-unsafe": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "yaml-merge-key-unsafe"); },
  "yarn-berry-integrity": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "yarn-berry-integrity"); },
  "yarn-berry-zipfs": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "yarn-berry-zipfs"); },
  "yjs-doc": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "yjs-doc"); },
  "yubikey-fido": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "yubikey-fido"); },
  "yugabyte-ysql": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "yugabyte-ysql"); },
  "zendesk-sunshine-conversations": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "zendesk-sunshine-conversations"); },
  "zendesk-ticket-api": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "zendesk-ticket-api"); },
  "zfs-scrub-io": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "zfs-scrub-io"); },
  "zscaler-zpa": () => { if (process.env.OBLIXA_SWEEP_STUB_VERBOSE === "1") console.debug("[sweep-stub]", "zscaler-zpa"); },
};
