import {
  BadgeCheck,
  BarChart3,
  Bell,
  BellRing,
  Boxes,
  Building2,
  CalendarClock,
  ClipboardCheck,
  CreditCard,
  Download,
  FileCheck2,
  Files,
  GitBranch,
  Grid2x2,
  LayoutDashboard,
  ListTodo,
  Megaphone,
  SearchCheck,
  Settings,
  Shield,
  ShieldCheck,
  Upload,
  Users,
  UserRound,
  type LucideIcon,
} from "lucide-react";
import type { SidebarItemModel } from "../sidebar-model";

// Icons for the primary sidebar plus the extra cmd-K-only destinations
// (profile / workspace-identity / team / imports / security-account /
// notifications / export). The latter group never renders in the rail — but the
// NavItem icon union is shared, so the record must be exhaustive.
export const iconByKey: Record<NonNullable<SidebarItemModel["icon"]>, LucideIcon> = {
  dashboard: LayoutDashboard,
  review: SearchCheck,
  contracts: Files,
  tasks: ListTodo,
  renewals: CalendarClock,
  exceptions: BellRing,
  evidence: FileCheck2,
  reports: BarChart3,
  decisions: BadgeCheck,
  campaigns: Megaphone,
  assurance: Shield,
  relationships: GitBranch,
  programs: Boxes,
  settings: Settings,
  billing: CreditCard,
  more: Grid2x2,
  profile: UserRound,
  "workspace-identity": Building2,
  team: Users,
  imports: Upload,
  "security-account": ShieldCheck,
  notifications: Bell,
  export: Download,
  "review-fields": ClipboardCheck,
};
