-- Generated by scripts/check-sql-policy-predicate-equivalence.mjs --write
-- Read-only SQL for future linked predicate-equivalence verification.
-- This file does not create, alter, or drop policies and does not claim production verification.

-- Policy: public.v10_activation_state:Members can read V10 activation
-- Neutral policy candidate: public.activation_state:Members can read activation
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_activation_state
), neutral_visible as (
  select count(*)::bigint as row_count from public.activation_state
)
select
  'public.v10_activation_state:Members can read V10 activation'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_activation_state:Members can read V10 activation'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_advanced_assurance_linked_records:Members can read V10 advanced assurance linked records
-- Neutral policy candidate: public.advanced_assurance_linked_records:Members can read advanced assurance linked records
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_advanced_assurance_linked_records
), neutral_visible as (
  select count(*)::bigint as row_count from public.advanced_assurance_linked_records
)
select
  'public.v10_advanced_assurance_linked_records:Members can read V10 advanced assurance linked records'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_advanced_assurance_linked_records:Members can read V10 advanced assurance linked records'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_approval_records:Members can read V10 approval records
-- Neutral policy candidate: public.approval_records:Members can read approval records
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_approval_records
), neutral_visible as (
  select count(*)::bigint as row_count from public.approval_records
)
select
  'public.v10_approval_records:Members can read V10 approval records'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_approval_records:Members can read V10 approval records'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_audit_events:Members can read V10 audit
-- Neutral policy candidate: public.audit_events:Members can read audit
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_audit_events
), neutral_visible as (
  select count(*)::bigint as row_count from public.audit_events
)
select
  'public.v10_audit_events:Members can read V10 audit'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_audit_events:Members can read V10 audit'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_command_search_index:Members can read V10 command search
-- Neutral policy candidate: public.command_search_index:Members can read command search
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_command_search_index
), neutral_visible as (
  select count(*)::bigint as row_count from public.command_search_index
)
select
  'public.v10_command_search_index:Members can read V10 command search'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_command_search_index:Members can read V10 command search'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_contract_activity_events:Members can read V10 contract activity
-- Neutral policy candidate: public.contract_activity_events:Members can read contract activity
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_contract_activity_events
), neutral_visible as (
  select count(*)::bigint as row_count from public.contract_activity_events
)
select
  'public.v10_contract_activity_events:Members can read V10 contract activity'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_contract_activity_events:Members can read V10 contract activity'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_contract_health_snapshots:Members can read V10 health
-- Neutral policy candidate: public.contract_health_snapshots:Members can read health
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_contract_health_snapshots
), neutral_visible as (
  select count(*)::bigint as row_count from public.contract_health_snapshots
)
select
  'public.v10_contract_health_snapshots:Members can read V10 health'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_contract_health_snapshots:Members can read V10 health'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_denominator_locks:Members can read V10 denominator locks
-- Neutral policy candidate: public.denominator_locks:Members can read denominator locks
-- Command: select
-- Roles: default/public
-- Legacy USING: exists ( select 1 from public.organization_members om where om.organization_id = v10_denominator_locks.organization_id and om.user_id = auth.uid() )
-- Neutral USING candidate: exists ( select 1 from public.organization_members om where om.organization_id = denominator_locks.organization_id and om.user_id = auth.uid() )
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_denominator_locks
), neutral_visible as (
  select count(*)::bigint as row_count from public.denominator_locks
)
select
  'public.v10_denominator_locks:Members can read V10 denominator locks'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_denominator_locks:Members can read V10 denominator locks'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_evidence_request_statuses:Members can read V10 evidence statuses
-- Neutral policy candidate: public.evidence_request_statuses:Members can read evidence statuses
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_evidence_request_statuses
), neutral_visible as (
  select count(*)::bigint as row_count from public.evidence_request_statuses
)
select
  'public.v10_evidence_request_statuses:Members can read V10 evidence statuses'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_evidence_request_statuses:Members can read V10 evidence statuses'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_exception_records:Members can read V10 exception records
-- Neutral policy candidate: public.exception_records:Members can read exception records
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_exception_records
), neutral_visible as (
  select count(*)::bigint as row_count from public.exception_records
)
select
  'public.v10_exception_records:Members can read V10 exception records'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_exception_records:Members can read V10 exception records'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_external_blocker_records:Members can read V10 external blocker records
-- Neutral policy candidate: public.external_blocker_records:Members can read external blocker records
-- Command: select
-- Roles: default/public
-- Legacy USING: exists ( select 1 from public.organization_members om where om.organization_id = v10_external_blocker_records.organization_id and om.user_id = auth.uid() )
-- Neutral USING candidate: exists ( select 1 from public.organization_members om where om.organization_id = external_blocker_records.organization_id and om.user_id = auth.uid() )
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_external_blocker_records
), neutral_visible as (
  select count(*)::bigint as row_count from public.external_blocker_records
)
select
  'public.v10_external_blocker_records:Members can read V10 external blocker records'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_external_blocker_records:Members can read V10 external blocker records'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_external_evidence_submissions:Members can read V10 external evidence submissions
-- Neutral policy candidate: public.external_evidence_submissions:Members can read external evidence submissions
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_external_evidence_submissions
), neutral_visible as (
  select count(*)::bigint as row_count from public.external_evidence_submissions
)
select
  'public.v10_external_evidence_submissions:Members can read V10 external evidence submissions'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_external_evidence_submissions:Members can read V10 external evidence submissions'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_field_provenance_records:Members can read V10 field provenance
-- Neutral policy candidate: public.field_provenance_records:Members can read field provenance
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_field_provenance_records
), neutral_visible as (
  select count(*)::bigint as row_count from public.field_provenance_records
)
select
  'public.v10_field_provenance_records:Members can read V10 field provenance'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_field_provenance_records:Members can read V10 field provenance'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_fixture_manifests:Members can read V10 fixture manifests
-- Neutral policy candidate: public.fixture_manifests:Members can read fixture manifests
-- Command: select
-- Roles: default/public
-- Legacy USING: exists ( select 1 from public.organization_members om where om.organization_id = v10_fixture_manifests.organization_id and om.user_id = auth.uid() )
-- Neutral USING candidate: exists ( select 1 from public.organization_members om where om.organization_id = fixture_manifests.organization_id and om.user_id = auth.uid() )
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_fixture_manifests
), neutral_visible as (
  select count(*)::bigint as row_count from public.fixture_manifests
)
select
  'public.v10_fixture_manifests:Members can read V10 fixture manifests'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_fixture_manifests:Members can read V10 fixture manifests'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_fixture_teardown_records:Members can read V10 fixture teardown records
-- Neutral policy candidate: public.fixture_teardown_records:Members can read fixture teardown records
-- Command: select
-- Roles: default/public
-- Legacy USING: exists ( select 1 from public.organization_members om where om.organization_id = v10_fixture_teardown_records.organization_id and om.user_id = auth.uid() )
-- Neutral USING candidate: exists ( select 1 from public.organization_members om where om.organization_id = fixture_teardown_records.organization_id and om.user_id = auth.uid() )
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_fixture_teardown_records
), neutral_visible as (
  select count(*)::bigint as row_count from public.fixture_teardown_records
)
select
  'public.v10_fixture_teardown_records:Members can read V10 fixture teardown records'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_fixture_teardown_records:Members can read V10 fixture teardown records'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_job_run_visibility:Members can read V10 jobs
-- Neutral policy candidate: public.job_run_visibility:Members can read jobs
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_job_run_visibility
), neutral_visible as (
  select count(*)::bigint as row_count from public.job_run_visibility
)
select
  'public.v10_job_run_visibility:Members can read V10 jobs'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_job_run_visibility:Members can read V10 jobs'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_metric_runs:Members can read V10 metric runs
-- Neutral policy candidate: public.metric_runs:Members can read metric runs
-- Command: select
-- Roles: default/public
-- Legacy USING: exists ( select 1 from public.organization_members om where om.organization_id = v10_metric_runs.organization_id and om.user_id = auth.uid() )
-- Neutral USING candidate: exists ( select 1 from public.organization_members om where om.organization_id = metric_runs.organization_id and om.user_id = auth.uid() )
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_metric_runs
), neutral_visible as (
  select count(*)::bigint as row_count from public.metric_runs
)
select
  'public.v10_metric_runs:Members can read V10 metric runs'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_metric_runs:Members can read V10 metric runs'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_mutation_idempotency:No direct member access V10 mutation idempotency
-- Neutral policy candidate: public.mutation_idempotency:No direct member access mutation idempotency
-- Command: all
-- Roles: default/public
-- Legacy USING: false
-- Neutral USING candidate: false
-- Legacy WITH CHECK: false
-- Neutral WITH CHECK candidate: false
-- Manual linked verification required: non-SELECT policy command cannot be proven by read-only row-count comparison.
select
  'public.v10_mutation_idempotency:No direct member access V10 mutation idempotency'::text as policy_identity,
  'manual_non_select_policy_placeholder'::text as verification_kind,
  'all'::text as policy_command,
  'Run linked read-only catalog and role-context verification before creating neutral policies.'::text as expected_future_command;


-- Policy: public.v10_notification_deliveries:Members can read V10 notification deliveries
-- Neutral policy candidate: public.notification_deliveries:Members can read notification deliveries
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_notification_deliveries
), neutral_visible as (
  select count(*)::bigint as row_count from public.notification_deliveries
)
select
  'public.v10_notification_deliveries:Members can read V10 notification deliveries'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_notification_deliveries:Members can read V10 notification deliveries'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_obligation_records:Members can read V10 obligation records
-- Neutral policy candidate: public.obligation_records:Members can read obligation records
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_obligation_records
), neutral_visible as (
  select count(*)::bigint as row_count from public.obligation_records
)
select
  'public.v10_obligation_records:Members can read V10 obligation records'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_obligation_records:Members can read V10 obligation records'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_promotion_decisions:Members can read V10 promotion decisions
-- Neutral policy candidate: public.promotion_decisions:Members can read promotion decisions
-- Command: select
-- Roles: default/public
-- Legacy USING: exists ( select 1 from public.organization_members om where om.organization_id = v10_promotion_decisions.organization_id and om.user_id = auth.uid() )
-- Neutral USING candidate: exists ( select 1 from public.organization_members om where om.organization_id = promotion_decisions.organization_id and om.user_id = auth.uid() )
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_promotion_decisions
), neutral_visible as (
  select count(*)::bigint as row_count from public.promotion_decisions
)
select
  'public.v10_promotion_decisions:Members can read V10 promotion decisions'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_promotion_decisions:Members can read V10 promotion decisions'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_read_model_lineage:Members can read V10 read model lineage
-- Neutral policy candidate: public.read_model_lineage:Members can read read model lineage
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_read_model_lineage
), neutral_visible as (
  select count(*)::bigint as row_count from public.read_model_lineage
)
select
  'public.v10_read_model_lineage:Members can read V10 read model lineage'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_read_model_lineage:Members can read V10 read model lineage'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_read_model_refresh_jobs:Members can read V10 refresh jobs
-- Neutral policy candidate: public.read_model_refresh_jobs:Members can read refresh jobs
-- Command: select
-- Roles: default/public
-- Legacy USING: exists ( select 1 from public.organization_members om where om.organization_id = v10_read_model_refresh_jobs.organization_id and om.user_id = auth.uid() )
-- Neutral USING candidate: exists ( select 1 from public.organization_members om where om.organization_id = read_model_refresh_jobs.organization_id and om.user_id = auth.uid() )
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_read_model_refresh_jobs
), neutral_visible as (
  select count(*)::bigint as row_count from public.read_model_refresh_jobs
)
select
  'public.v10_read_model_refresh_jobs:Members can read V10 refresh jobs'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_read_model_refresh_jobs:Members can read V10 refresh jobs'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_read_model_rows:Members can read V10 read models
-- Neutral policy candidate: public.read_model_rows:Members can read read models
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_read_model_rows
), neutral_visible as (
  select count(*)::bigint as row_count from public.read_model_rows
)
select
  'public.v10_read_model_rows:Members can read V10 read models'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_read_model_rows:Members can read V10 read models'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_release_evidence_records:Members can read V10 release evidence records
-- Neutral policy candidate: public.release_evidence_records:Members can read release evidence records
-- Command: select
-- Roles: default/public
-- Legacy USING: exists ( select 1 from public.organization_members om where om.organization_id = v10_release_evidence_records.organization_id and om.user_id = auth.uid() )
-- Neutral USING candidate: exists ( select 1 from public.organization_members om where om.organization_id = release_evidence_records.organization_id and om.user_id = auth.uid() )
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_release_evidence_records
), neutral_visible as (
  select count(*)::bigint as row_count from public.release_evidence_records
)
select
  'public.v10_release_evidence_records:Members can read V10 release evidence records'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_release_evidence_records:Members can read V10 release evidence records'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_release_waivers:Members can read V10 release waivers
-- Neutral policy candidate: public.release_waivers:Members can read release waivers
-- Command: select
-- Roles: default/public
-- Legacy USING: exists ( select 1 from public.organization_members om where om.organization_id = v10_release_waivers.organization_id and om.user_id = auth.uid() )
-- Neutral USING candidate: exists ( select 1 from public.organization_members om where om.organization_id = release_waivers.organization_id and om.user_id = auth.uid() )
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_release_waivers
), neutral_visible as (
  select count(*)::bigint as row_count from public.release_waivers
)
select
  'public.v10_release_waivers:Members can read V10 release waivers'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_release_waivers:Members can read V10 release waivers'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_renewal_checkpoint_records:Members can read V10 renewal checkpoints
-- Neutral policy candidate: public.renewal_checkpoint_records:Members can read renewal checkpoints
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_renewal_checkpoint_records
), neutral_visible as (
  select count(*)::bigint as row_count from public.renewal_checkpoint_records
)
select
  'public.v10_renewal_checkpoint_records:Members can read V10 renewal checkpoints'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_renewal_checkpoint_records:Members can read V10 renewal checkpoints'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_renewal_posture_snapshots:Members can read V10 renewal posture
-- Neutral policy candidate: public.renewal_posture_snapshots:Members can read renewal posture
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_renewal_posture_snapshots
), neutral_visible as (
  select count(*)::bigint as row_count from public.renewal_posture_snapshots
)
select
  'public.v10_renewal_posture_snapshots:Members can read V10 renewal posture'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_renewal_posture_snapshots:Members can read V10 renewal posture'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_report_run_visibility:Members can read V10 report runs
-- Neutral policy candidate: public.report_run_visibility:Members can read report runs
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_report_run_visibility
), neutral_visible as (
  select count(*)::bigint as row_count from public.report_run_visibility
)
select
  'public.v10_report_run_visibility:Members can read V10 report runs'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_report_run_visibility:Members can read V10 report runs'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_runtime_artifacts:Members can read V10 runtime artifacts
-- Neutral policy candidate: public.runtime_artifacts:Members can read runtime artifacts
-- Command: select
-- Roles: default/public
-- Legacy USING: classification <> 'prohibited' and revoked_at is null and public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: classification <> 'prohibited' and revoked_at is null and public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_runtime_artifacts
), neutral_visible as (
  select count(*)::bigint as row_count from public.runtime_artifacts
)
select
  'public.v10_runtime_artifacts:Members can read V10 runtime artifacts'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_runtime_artifacts:Members can read V10 runtime artifacts'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_runtime_coverage_ledger:Members can read V10 runtime coverage ledger
-- Neutral policy candidate: public.runtime_coverage_ledger:Members can read runtime coverage ledger
-- Command: select
-- Roles: default/public
-- Legacy USING: organization_id is null or exists ( select 1 from public.organization_members om where om.organization_id = v10_runtime_coverage_ledger.organization_id and om.user_id = auth.uid() )
-- Neutral USING candidate: organization_id is null or exists ( select 1 from public.organization_members om where om.organization_id = runtime_coverage_ledger.organization_id and om.user_id = auth.uid() )
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_runtime_coverage_ledger
), neutral_visible as (
  select count(*)::bigint as row_count from public.runtime_coverage_ledger
)
select
  'public.v10_runtime_coverage_ledger:Members can read V10 runtime coverage ledger'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_runtime_coverage_ledger:Members can read V10 runtime coverage ledger'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_verification_command_results:Members can read V10 verification command results
-- Neutral policy candidate: public.verification_command_results:Members can read verification command results
-- Command: select
-- Roles: default/public
-- Legacy USING: exists ( select 1 from public.organization_members om where om.organization_id = v10_verification_command_results.organization_id and om.user_id = auth.uid() )
-- Neutral USING candidate: exists ( select 1 from public.organization_members om where om.organization_id = verification_command_results.organization_id and om.user_id = auth.uid() )
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_verification_command_results
), neutral_visible as (
  select count(*)::bigint as row_count from public.verification_command_results
)
select
  'public.v10_verification_command_results:Members can read V10 verification command results'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_verification_command_results:Members can read V10 verification command results'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;


-- Policy: public.v10_work_items:Members can read V10 work items
-- Neutral policy candidate: public.work_items:Members can read work items
-- Command: select
-- Roles: default/public
-- Legacy USING: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- Manual linked verification required: predicate depends on auth context or membership helpers.
with legacy_visible as (
  select count(*)::bigint as row_count from public.v10_work_items
), neutral_visible as (
  select count(*)::bigint as row_count from public.work_items
)
select
  'public.v10_work_items:Members can read V10 work items'::text as policy_identity,
  'manual_auth_context_select_comparison'::text as verification_kind,
  legacy_visible.row_count as legacy_visible_count,
  neutral_visible.row_count as neutral_visible_count,
  legacy_visible.row_count = neutral_visible.row_count as visible_count_matches
from legacy_visible, neutral_visible;
select
  'public.v10_work_items:Members can read V10 work items'::text as policy_identity,
  'manual_auth_context_required'::text as verification_kind,
  'Execute the count comparison under representative authenticated org-member contexts before policy migration.'::text as expected_future_command;
