-- Generated by scripts/check-sql-policy-forward-migration-blueprint.mjs --write
-- Non-executing SQL policy forward-migration blueprint.
-- This file contains comments and SELECT statements only.
-- It does not create, alter, or drop policies, grant privileges, backfill data, apply migrations, or remove legacy SQL objects.

-- Policy forward-migration blueprint: public.v10_activation_state:Members can read V10 activation
-- Neutral policy identity: public.activation_state:Members can read activation
-- Current neutral target is a view: public.activation_state
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read activation"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_activation_state:Members can read V10 activation'::text as legacy_policy,
  'public.activation_state:Members can read activation'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_advanced_assurance_linked_records:Members can read V10 advanced assurance linked records
-- Neutral policy identity: public.advanced_assurance_linked_records:Members can read advanced assurance linked records
-- Current neutral target is a view: public.advanced_assurance_linked_records
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read advanced assurance linked records"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_advanced_assurance_linked_records:Members can read V10 advanced assurance linked records'::text as legacy_policy,
  'public.advanced_assurance_linked_records:Members can read advanced assurance linked records'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_approval_records:Members can read V10 approval records
-- Neutral policy identity: public.approval_records:Members can read approval records
-- Current neutral target is a view: public.approval_records
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read approval records"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_approval_records:Members can read V10 approval records'::text as legacy_policy,
  'public.approval_records:Members can read approval records'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_audit_events:Members can read V10 audit
-- Neutral policy identity: public.audit_events:Members can read audit
-- Current neutral target is a view: public.audit_events
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read audit"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_audit_events:Members can read V10 audit'::text as legacy_policy,
  'public.audit_events:Members can read audit'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_command_search_index:Members can read V10 command search
-- Neutral policy identity: public.command_search_index:Members can read command search
-- Current neutral target is a view: public.command_search_index
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read command search"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_command_search_index:Members can read V10 command search'::text as legacy_policy,
  'public.command_search_index:Members can read command search'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_contract_activity_events:Members can read V10 contract activity
-- Neutral policy identity: public.contract_activity_events:Members can read contract activity
-- Current neutral target is a view: public.contract_activity_events
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read contract activity"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_contract_activity_events:Members can read V10 contract activity'::text as legacy_policy,
  'public.contract_activity_events:Members can read contract activity'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_contract_health_snapshots:Members can read V10 health
-- Neutral policy identity: public.contract_health_snapshots:Members can read health
-- Current neutral target is a view: public.contract_health_snapshots
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read health"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_contract_health_snapshots:Members can read V10 health'::text as legacy_policy,
  'public.contract_health_snapshots:Members can read health'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_denominator_locks:Members can read V10 denominator locks
-- Neutral policy identity: public.denominator_locks:Members can read denominator locks
-- Current neutral target is a view: public.denominator_locks
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: exists ( select 1 from public.organization_members om where om.organization_id = v10_denominator_locks.organization_id and om.user_id = auth.uid() )
-- Neutral USING predicate candidate: exists ( select 1 from public.organization_members om where om.organization_id = denominator_locks.organization_id and om.user_id = auth.uid() )
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read denominator locks"
--   on <future policy-capable neutral table>
--   for select
--   using (exists ( select 1 from public.organization_members om where om.organization_id = denominator_locks.organization_id and om.user_id = auth.uid() ));
select
  'public.v10_denominator_locks:Members can read V10 denominator locks'::text as legacy_policy,
  'public.denominator_locks:Members can read denominator locks'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_evidence_request_statuses:Members can read V10 evidence statuses
-- Neutral policy identity: public.evidence_request_statuses:Members can read evidence statuses
-- Current neutral target is a view: public.evidence_request_statuses
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read evidence statuses"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_evidence_request_statuses:Members can read V10 evidence statuses'::text as legacy_policy,
  'public.evidence_request_statuses:Members can read evidence statuses'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_exception_records:Members can read V10 exception records
-- Neutral policy identity: public.exception_records:Members can read exception records
-- Current neutral target is a view: public.exception_records
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read exception records"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_exception_records:Members can read V10 exception records'::text as legacy_policy,
  'public.exception_records:Members can read exception records'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_external_blocker_records:Members can read V10 external blocker records
-- Neutral policy identity: public.external_blocker_records:Members can read external blocker records
-- Current neutral target is a view: public.external_blocker_records
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: exists ( select 1 from public.organization_members om where om.organization_id = v10_external_blocker_records.organization_id and om.user_id = auth.uid() )
-- Neutral USING predicate candidate: exists ( select 1 from public.organization_members om where om.organization_id = external_blocker_records.organization_id and om.user_id = auth.uid() )
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read external blocker records"
--   on <future policy-capable neutral table>
--   for select
--   using (exists ( select 1 from public.organization_members om where om.organization_id = external_blocker_records.organization_id and om.user_id = auth.uid() ));
select
  'public.v10_external_blocker_records:Members can read V10 external blocker records'::text as legacy_policy,
  'public.external_blocker_records:Members can read external blocker records'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_external_evidence_submissions:Members can read V10 external evidence submissions
-- Neutral policy identity: public.external_evidence_submissions:Members can read external evidence submissions
-- Current neutral target is a view: public.external_evidence_submissions
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read external evidence submissions"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_external_evidence_submissions:Members can read V10 external evidence submissions'::text as legacy_policy,
  'public.external_evidence_submissions:Members can read external evidence submissions'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_field_provenance_records:Members can read V10 field provenance
-- Neutral policy identity: public.field_provenance_records:Members can read field provenance
-- Current neutral target is a view: public.field_provenance_records
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read field provenance"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_field_provenance_records:Members can read V10 field provenance'::text as legacy_policy,
  'public.field_provenance_records:Members can read field provenance'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_fixture_manifests:Members can read V10 fixture manifests
-- Neutral policy identity: public.fixture_manifests:Members can read fixture manifests
-- Current neutral target is a view: public.fixture_manifests
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: exists ( select 1 from public.organization_members om where om.organization_id = v10_fixture_manifests.organization_id and om.user_id = auth.uid() )
-- Neutral USING predicate candidate: exists ( select 1 from public.organization_members om where om.organization_id = fixture_manifests.organization_id and om.user_id = auth.uid() )
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read fixture manifests"
--   on <future policy-capable neutral table>
--   for select
--   using (exists ( select 1 from public.organization_members om where om.organization_id = fixture_manifests.organization_id and om.user_id = auth.uid() ));
select
  'public.v10_fixture_manifests:Members can read V10 fixture manifests'::text as legacy_policy,
  'public.fixture_manifests:Members can read fixture manifests'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_fixture_teardown_records:Members can read V10 fixture teardown records
-- Neutral policy identity: public.fixture_teardown_records:Members can read fixture teardown records
-- Current neutral target is a view: public.fixture_teardown_records
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: exists ( select 1 from public.organization_members om where om.organization_id = v10_fixture_teardown_records.organization_id and om.user_id = auth.uid() )
-- Neutral USING predicate candidate: exists ( select 1 from public.organization_members om where om.organization_id = fixture_teardown_records.organization_id and om.user_id = auth.uid() )
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read fixture teardown records"
--   on <future policy-capable neutral table>
--   for select
--   using (exists ( select 1 from public.organization_members om where om.organization_id = fixture_teardown_records.organization_id and om.user_id = auth.uid() ));
select
  'public.v10_fixture_teardown_records:Members can read V10 fixture teardown records'::text as legacy_policy,
  'public.fixture_teardown_records:Members can read fixture teardown records'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_job_run_visibility:Members can read V10 jobs
-- Neutral policy identity: public.job_run_visibility:Members can read jobs
-- Current neutral target is a view: public.job_run_visibility
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read jobs"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_job_run_visibility:Members can read V10 jobs'::text as legacy_policy,
  'public.job_run_visibility:Members can read jobs'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_metric_runs:Members can read V10 metric runs
-- Neutral policy identity: public.metric_runs:Members can read metric runs
-- Current neutral target is a view: public.metric_runs
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: exists ( select 1 from public.organization_members om where om.organization_id = v10_metric_runs.organization_id and om.user_id = auth.uid() )
-- Neutral USING predicate candidate: exists ( select 1 from public.organization_members om where om.organization_id = metric_runs.organization_id and om.user_id = auth.uid() )
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read metric runs"
--   on <future policy-capable neutral table>
--   for select
--   using (exists ( select 1 from public.organization_members om where om.organization_id = metric_runs.organization_id and om.user_id = auth.uid() ));
select
  'public.v10_metric_runs:Members can read V10 metric runs'::text as legacy_policy,
  'public.metric_runs:Members can read metric runs'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_mutation_idempotency:No direct member access V10 mutation idempotency
-- Neutral policy identity: public.mutation_idempotency:No direct member access mutation idempotency
-- Current neutral target is a view: public.mutation_idempotency
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: manual_catalog_and_role_context_for_non_select_policy
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: all
-- Roles: default/public
-- Legacy USING predicate: false
-- Neutral USING predicate candidate: false
-- Legacy WITH CHECK predicate: false
-- Neutral WITH CHECK predicate candidate: false
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "No direct member access mutation idempotency"
--   on <future policy-capable neutral table>
--   for all
--   using (false);
--   with check (false);
select
  'public.v10_mutation_idempotency:No direct member access V10 mutation idempotency'::text as legacy_policy,
  'public.mutation_idempotency:No direct member access mutation idempotency'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'manual_catalog_and_role_context_for_non_select_policy'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_notification_deliveries:Members can read V10 notification deliveries
-- Neutral policy identity: public.notification_deliveries:Members can read notification deliveries
-- Current neutral target is a view: public.notification_deliveries
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read notification deliveries"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_notification_deliveries:Members can read V10 notification deliveries'::text as legacy_policy,
  'public.notification_deliveries:Members can read notification deliveries'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_obligation_records:Members can read V10 obligation records
-- Neutral policy identity: public.obligation_records:Members can read obligation records
-- Current neutral target is a view: public.obligation_records
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read obligation records"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_obligation_records:Members can read V10 obligation records'::text as legacy_policy,
  'public.obligation_records:Members can read obligation records'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_promotion_decisions:Members can read V10 promotion decisions
-- Neutral policy identity: public.promotion_decisions:Members can read promotion decisions
-- Current neutral target is a view: public.promotion_decisions
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: exists ( select 1 from public.organization_members om where om.organization_id = v10_promotion_decisions.organization_id and om.user_id = auth.uid() )
-- Neutral USING predicate candidate: exists ( select 1 from public.organization_members om where om.organization_id = promotion_decisions.organization_id and om.user_id = auth.uid() )
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read promotion decisions"
--   on <future policy-capable neutral table>
--   for select
--   using (exists ( select 1 from public.organization_members om where om.organization_id = promotion_decisions.organization_id and om.user_id = auth.uid() ));
select
  'public.v10_promotion_decisions:Members can read V10 promotion decisions'::text as legacy_policy,
  'public.promotion_decisions:Members can read promotion decisions'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_read_model_lineage:Members can read V10 read model lineage
-- Neutral policy identity: public.read_model_lineage:Members can read read model lineage
-- Current neutral target is a view: public.read_model_lineage
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read read model lineage"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_read_model_lineage:Members can read V10 read model lineage'::text as legacy_policy,
  'public.read_model_lineage:Members can read read model lineage'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_read_model_refresh_jobs:Members can read V10 refresh jobs
-- Neutral policy identity: public.read_model_refresh_jobs:Members can read refresh jobs
-- Current neutral target is a view: public.read_model_refresh_jobs
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: exists ( select 1 from public.organization_members om where om.organization_id = v10_read_model_refresh_jobs.organization_id and om.user_id = auth.uid() )
-- Neutral USING predicate candidate: exists ( select 1 from public.organization_members om where om.organization_id = read_model_refresh_jobs.organization_id and om.user_id = auth.uid() )
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read refresh jobs"
--   on <future policy-capable neutral table>
--   for select
--   using (exists ( select 1 from public.organization_members om where om.organization_id = read_model_refresh_jobs.organization_id and om.user_id = auth.uid() ));
select
  'public.v10_read_model_refresh_jobs:Members can read V10 refresh jobs'::text as legacy_policy,
  'public.read_model_refresh_jobs:Members can read refresh jobs'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_read_model_rows:Members can read V10 read models
-- Neutral policy identity: public.read_model_rows:Members can read read models
-- Current neutral target is a view: public.read_model_rows
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read read models"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_read_model_rows:Members can read V10 read models'::text as legacy_policy,
  'public.read_model_rows:Members can read read models'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_release_evidence_records:Members can read V10 release evidence records
-- Neutral policy identity: public.release_evidence_records:Members can read release evidence records
-- Current neutral target is a view: public.release_evidence_records
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: exists ( select 1 from public.organization_members om where om.organization_id = v10_release_evidence_records.organization_id and om.user_id = auth.uid() )
-- Neutral USING predicate candidate: exists ( select 1 from public.organization_members om where om.organization_id = release_evidence_records.organization_id and om.user_id = auth.uid() )
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read release evidence records"
--   on <future policy-capable neutral table>
--   for select
--   using (exists ( select 1 from public.organization_members om where om.organization_id = release_evidence_records.organization_id and om.user_id = auth.uid() ));
select
  'public.v10_release_evidence_records:Members can read V10 release evidence records'::text as legacy_policy,
  'public.release_evidence_records:Members can read release evidence records'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_release_waivers:Members can read V10 release waivers
-- Neutral policy identity: public.release_waivers:Members can read release waivers
-- Current neutral target is a view: public.release_waivers
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: exists ( select 1 from public.organization_members om where om.organization_id = v10_release_waivers.organization_id and om.user_id = auth.uid() )
-- Neutral USING predicate candidate: exists ( select 1 from public.organization_members om where om.organization_id = release_waivers.organization_id and om.user_id = auth.uid() )
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read release waivers"
--   on <future policy-capable neutral table>
--   for select
--   using (exists ( select 1 from public.organization_members om where om.organization_id = release_waivers.organization_id and om.user_id = auth.uid() ));
select
  'public.v10_release_waivers:Members can read V10 release waivers'::text as legacy_policy,
  'public.release_waivers:Members can read release waivers'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_renewal_checkpoint_records:Members can read V10 renewal checkpoints
-- Neutral policy identity: public.renewal_checkpoint_records:Members can read renewal checkpoints
-- Current neutral target is a view: public.renewal_checkpoint_records
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read renewal checkpoints"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_renewal_checkpoint_records:Members can read V10 renewal checkpoints'::text as legacy_policy,
  'public.renewal_checkpoint_records:Members can read renewal checkpoints'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_renewal_posture_snapshots:Members can read V10 renewal posture
-- Neutral policy identity: public.renewal_posture_snapshots:Members can read renewal posture
-- Current neutral target is a view: public.renewal_posture_snapshots
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read renewal posture"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_renewal_posture_snapshots:Members can read V10 renewal posture'::text as legacy_policy,
  'public.renewal_posture_snapshots:Members can read renewal posture'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_report_run_visibility:Members can read V10 report runs
-- Neutral policy identity: public.report_run_visibility:Members can read report runs
-- Current neutral target is a view: public.report_run_visibility
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read report runs"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_report_run_visibility:Members can read V10 report runs'::text as legacy_policy,
  'public.report_run_visibility:Members can read report runs'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_runtime_artifacts:Members can read V10 runtime artifacts
-- Neutral policy identity: public.runtime_artifacts:Members can read runtime artifacts
-- Current neutral target is a view: public.runtime_artifacts
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: classification <> 'prohibited' and revoked_at is null and public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: classification <> 'prohibited' and revoked_at is null and public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read runtime artifacts"
--   on <future policy-capable neutral table>
--   for select
--   using (classification <> 'prohibited' and revoked_at is null and public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_runtime_artifacts:Members can read V10 runtime artifacts'::text as legacy_policy,
  'public.runtime_artifacts:Members can read runtime artifacts'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_runtime_coverage_ledger:Members can read V10 runtime coverage ledger
-- Neutral policy identity: public.runtime_coverage_ledger:Members can read runtime coverage ledger
-- Current neutral target is a view: public.runtime_coverage_ledger
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: organization_id is null or exists ( select 1 from public.organization_members om where om.organization_id = v10_runtime_coverage_ledger.organization_id and om.user_id = auth.uid() )
-- Neutral USING predicate candidate: organization_id is null or exists ( select 1 from public.organization_members om where om.organization_id = runtime_coverage_ledger.organization_id and om.user_id = auth.uid() )
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read runtime coverage ledger"
--   on <future policy-capable neutral table>
--   for select
--   using (organization_id is null or exists ( select 1 from public.organization_members om where om.organization_id = runtime_coverage_ledger.organization_id and om.user_id = auth.uid() ));
select
  'public.v10_runtime_coverage_ledger:Members can read V10 runtime coverage ledger'::text as legacy_policy,
  'public.runtime_coverage_ledger:Members can read runtime coverage ledger'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_verification_command_results:Members can read V10 verification command results
-- Neutral policy identity: public.verification_command_results:Members can read verification command results
-- Current neutral target is a view: public.verification_command_results
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: exists ( select 1 from public.organization_members om where om.organization_id = v10_verification_command_results.organization_id and om.user_id = auth.uid() )
-- Neutral USING predicate candidate: exists ( select 1 from public.organization_members om where om.organization_id = verification_command_results.organization_id and om.user_id = auth.uid() )
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read verification command results"
--   on <future policy-capable neutral table>
--   for select
--   using (exists ( select 1 from public.organization_members om where om.organization_id = verification_command_results.organization_id and om.user_id = auth.uid() ));
select
  'public.v10_verification_command_results:Members can read V10 verification command results'::text as legacy_policy,
  'public.verification_command_results:Members can read verification command results'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;


-- Policy forward-migration blueprint: public.v10_work_items:Members can read V10 work items
-- Neutral policy identity: public.work_items:Members can read work items
-- Current neutral target is a view: public.work_items
-- Required future target: neutral_policy_capable_table_or_equivalent_target_required
-- Required linked verification context: representative_authenticated_org_member_contexts
-- Future migration gate: Add a policy-capable neutral target, run linked read-only predicate-equivalence verification, then create neutral policies in a separate reviewed forward migration.
-- Command: select
-- Roles: default/public
-- Legacy USING predicate: public.v10_member_can_read(organization_id, required_role_minimum, visibility_state)
-- Neutral USING predicate candidate: public.member_can_read(organization_id, required_role_minimum, visibility_state)
-- FUTURE DDL PLACEHOLDER (comment only; do not execute from this file):
-- create policy "Members can read work items"
--   on <future policy-capable neutral table>
--   for select
--   using (public.member_can_read(organization_id, required_role_minimum, visibility_state));
select
  'public.v10_work_items:Members can read V10 work items'::text as legacy_policy,
  'public.work_items:Members can read work items'::text as neutral_policy,
  'requires_forward_migration'::text as blueprint_status,
  'neutral_target_is_view_requires_policy_migration'::text as blocker_class,
  'neutral_policy_capable_table_or_equivalent_target_required'::text as future_target_requirement,
  'representative_authenticated_org_member_contexts'::text as required_linked_verification_context,
  'npm run check:sql-policy-forward-migration-blueprint'::text as validation_command,
  false::boolean as migratable_in_this_pass;
