const COUNT_AWARE_LABELS: Record<string, string> = {
  "Active requests": "Active request",
  "Active approver slots": "Active approver slot",
  "Blocked scenarios": "Blocked scenario",
  "Clarification loops": "Clarification loop",
  "Completed runs": "Completed run",
  "Contracts in view": "Contract in view",
  "Contracts processed": "Contract processed",
  "Contracts tracked": "Contract tracked",
  "Contracts waiting": "Contract waiting",
  "Contracts on key": "Contract on key",
  "Critical issues": "Critical issue",
  "Critical exceptions": "Critical exception",
  "Critical gaps": "Critical gap",
  "Digest executions": "Digest execution",
  "Duplicate groups": "Duplicate group",
  "Email digest runs": "Email digest run",
  "Eligible contracts": "Eligible contract",
  "Failed deliveries": "Failed delivery",
  "Failed runs": "Failed run",
  "Field comments (sample)": "Field comment (sample)",
  Forecasts: "Forecast",
  Interventions: "Intervention",
  "Missed dates prevented": "Missed date prevented",
  "Missing approved dates": "Missing approved date",
  "Open items": "Open item",
  "Open exceptions": "Open exception",
  "Open findings": "Open finding",
  "Open obligations": "Open obligation",
  "Open tasks": "Open task",
  "Orphaned files": "Orphaned file",
  "Outbound backlog": "Outbound backlog item",
  "Pending fields": "Pending field",
  "Pending approvals": "Pending approval",
  Policies: "Policy",
  "Policy evaluations": "Policy evaluation",
  "Recorded interventions": "Recorded intervention",
  "Report packs": "Report pack",
  "Rows shown": "Row shown",
  "Saved templates": "Saved template",
  "Sampled queue": "Sampled queue item",
  "Stale records": "Stale record",
  "Status transitions": "Status transition",
  Subscriptions: "Subscription",
  Templates: "Template",
  "Timeline events": "Timeline event",
  "Tasks completed": "Task completed",
  "Unread notifications": "Unread notification",
  "Unresolved gaps": "Unresolved gap",
  "Upcoming checkpoints": "Upcoming checkpoint",
  "Watchlisted contracts": "Watchlisted contract",
  "Weak field signals": "Weak field signal",
  "Weekly operators": "Weekly operator",
  "active critical": "active critical",
  "approved in this slice": "approved in this slice",
  "awaiting signoff": "awaiting signoff",
  "awaiting start": "awaiting start",
  "campaigns running": "campaign running",
  "completed runs": "completed run",
  "current approvals": "current approval",
  "contracts in queue": "contract in queue",
  "contracts loaded": "contract loaded",
  "contracts need extra follow-up": "contract needs extra follow-up",
  "contracts on this page": "contract on this page",
  "contracts running": "contract running",
  "contracts with blockers or owner gaps": "contract with blocker or owner gap",
  "failed in sample": "failed in sample",
  "in studio": "in studio",
  "latest samples": "latest sample",
  "need action": "needs action",
  "need recovery": "needs recovery",
  "need unblock plan": "needs unblock plan",
  "open or in progress": "open or in progress",
  "paused campaigns": "paused campaign",
  "recent runs": "recent run",
  "recent rows": "recent row",
  "recent sample": "recent sample",
  "resolved samples": "resolved sample",
  rows: "row",
  "saved templates": "saved template",
  "still need owner": "still needs owner",
  "still awaiting review": "still awaiting review",
  "still requested": "still requested",
  "tracked seats": "tracked seat",
  "undelivered samples": "undelivered sample",
  "with at least one item": "with at least one item",
};

export function countAwareLabel(label: string, count: number | null): string {
  if (count !== 1) return label;
  return COUNT_AWARE_LABELS[label] ?? label;
}
